### ISSUE TITLE
Diverse Errors

### ISSUE THREAD

**Issue by Schrader1** [afuerhoff/ioBroker.fb-checkpresence#10]
Adapter geht immer wieder auf Rot, Hatte den js.contoller geupdatet, dachte daran lag es . Hatte ein rollback des js.controlers auf 2.2.1 gemacht, dies brachte aber kein erfolg.
Der adapter lief vorher.
liegt der Fehler bei mir?

> fb-checkpresence.0	2020-02-18 22:25:10.124	info	(10521) start fb-checkpresence: ip-address: 192.168.158.1 polling interval: 1 Min.
fb-checkpresence.0	2020-02-18 22:25:10.108	info	(10521) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v10.19.0
host.iobroker	2020-02-18 22:25:09.319	info	instance system.adapter.fb-checkpresence.0 started with pid 10521
host.iobroker	2020-02-18 22:24:39.313	info	Restart adapter system.adapter.fb-checkpresence.0 because enabled
host.iobroker	2020-02-18 22:24:39.313	info	instance system.adapter.fb-checkpresence.0 terminated with code 0 (NO_ERROR)
host.iobroker	2020-02-18 22:24:39.313	error	Caught by controller[0]: at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
host.iobroker	2020-02-18 22:24:39.313	error	Caught by controller[0]: at Request.emit (events.js:198:13)
host.iobroker	2020-02-18 22:24:39.313	error	Caught by controller[0]: at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.iobroker	2020-02-18 22:24:39.313	error	Caught by controller[0]: at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
host.iobroker	2020-02-18 22:24:39.313	error	Caught by controller[0]: at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: at Parser.emit (events.js:198:13)
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
host.iobroker	2020-02-18 22:24:39.312	error	Caught by controller[0]: TypeError: Cannot read property 'search' of undefined
fb-checkpresence.0	2020-02-18 22:24:38.802	info	(8903) Terminated (NO_ERROR): Without reason
fb-checkpresence.0	2020-02-18 22:24:38.801	info	(8903) terminating
fb-checkpresence.0	2020-02-18 22:24:38.798	error	(8903) onReady: read ECONNRESET
fb-checkpresence.0	2020-02-18 22:24:38.797	info	(8903) cleaned everything up...
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Request.emit (events.js:198:13)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:36:17)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at exports.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:369:19)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:5:59)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:327:16)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Parser.emit (events.js:198:13)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at Parser.<anonymous> (/opt/iobroker/node_modules/iobroker.fb-checkpresence/node_modules/xml2js/lib/parser.js:308:18)
fb-checkpresence.0	2020-02-18 22:24:38.796	error	at /opt/iobroker/node_modules/iobroker.fb-checkpresence/lib/fb.js:37:57
fb-checkpresence.0	2020-02-18 22:24:38.796	error	(8903) TypeError: Cannot read property 'search' of undefined
fb-checkpresence.0	2020-02-18 22:24:38.796	error	(8903) uncaught exception: Cannot read property 'search' of undefined

**Comment by afuerhoff** [comment]
Bitte einmal die neueste Version von Github laden und den Loglevel auf debug stellen. Dann am besten vom Start des Adapters bis zur Fehlermeldung den Log im Forum posten.

**Comment by afuerhoff** [comment]
Hallo, hast Du den Fehler immer noch? Ich hab die Version 0.3.0 released.

**Comment by afuerhoff** [comment]
Hallo, habe vor kurzem eine neue Version auf Github freigegeben. Kannst du mit der mal prüfen, ob die Fehler nicht mehr kommen.

**Comment by afuerhoff** [comment]
Hallo, ich schließe den Issue, da ich keine Rückmeldung mehr bekommen habe.
