### ISSUE TITLE
Integrate X_AVM-DE_Disallow in fb-devices.json's

### ISSUE THREAD

**Issue by afuerhoff** [afuerhoff/ioBroker.fb-checkpresence#110]
Currently in JSON fb-checkpresence.0.fb-devices.json shows:
{
"Hostname": "HOSTNAM",
"IP-Address": "192.168.192.XXX",
"MAC-Address": "47:11:xx:XX",
"Active": "false",
"Type": "-"
}

in ioBrokler Objects the disable status is shown:
fb-checkpresence.0.fb-devices.XXX.disabled

could you please integrate this info in JSON Objects

fb-checkpresence.0.fb-devices.json
fb-checkpresence.0.fb-devices.jsonActive
fb-checkpresence.0.fb-devices.jsonInactive
fb-checkpresence.0.fb-devices.html

**Comment by afuerhoff** [comment]
@zImage-de
Ich habe eine Testversion auf Github hochgeladen. Bitte einmal testen, ob es funktioniert.

**Comment by zImage-de** [comment]
Danke 
ich hatte zwar eine Fehlermeldung beim Installieren aus dem GITHUB (siehe unten) aber es scheint trotzdem zu funktionieren: 
<img width="654" alt="Bildschirmfoto 2022-05-22 um 22 17 39" src="https://user-images.githubusercontent.com/57576910/169714229-8b6a421f-f071-41ac-a5c4-b7ac55953efa.png">


$ iobroker url https://github.com/ioBroker/testing.git --host iobroker --debug
install ioBroker/testing#adf1974a1223cb100c9ded815450f7fe5cf6d564
NPM version: 8.7.0
Installing ioBroker/testing#adf1974a1223cb100c9ded815450f7fe5cf6d564... (System call)
npm WARN skipping integrity check for git dependency ssh://git@github.com/ioBroker/testing.git
added 46 packages in 3m
162 packages are looking for funding run `npm fund` for details
host.iobroker Cannot install ioBroker/testing#adf1974a1223cb100c9ded815450f7fe5cf6d564: 0
ERROR: Process exited with code 25

**Comment by afuerhoff** [comment]
Die URL und der Fehler kommen aber nicht vom Adapter.

**Comment by afuerhoff** [comment]
@zImage-de 
Die Funktion ist jetzt in der v1.1.15. Ist aber erstmal nur im Latest Repository.
