### ISSUE TITLE
Hinzufügen von Datenpunkt bei Family Member Device

### ISSUE THREAD

**Issue by iobFan** [afuerhoff/ioBroker.fb-checkpresence#111]
Hi, ich möchte basierend auf der Information, mit welchem Access Point (Repeater 1, Repeater 2, etc.) mein Gerät verbunden ist, verschiedene Skripte steuern.

Allerdings werden die WLAN Datenpunkte nur im "fb-devices" Ordner angezeigt und nicht unter "familyMembers". So wie ich sehe kann man nur die Datenpunkte unterhalb von "familyMembers" in kürzeren Intervallen Updaten. Die Ausführung des Skripts nach 1 Minute ist bei meinem Vorhaben deutlich zu lange..

Wäre es daher möglich, den Datenpunkt "link" im Ordner "WLAN" bei den "familyMembers" mit aufzunehmen, sodass dieser auch öfters (z.B. alle 10 sek) aktualisiert werden kann?

Vielen Dank vorab.

![image](https://user-images.githubusercontent.com/74504938/167677878-ef22c549-5384-4126-baa0-05a58c8abec6.png)

**Comment by afuerhoff** [comment]
Hallo,

ich könnte mir vorstellen, das generelle Intervall ebenfalls von 10s an einstellbar zu machen. Dann können alle Informationen entsprechend schnell gelesen werden. Ob das dann auf Kosten der Performance der Fritzbox geht kann ich allerdings nicht sagen.

**Comment by iobFan** [comment]
Das wäre super :) könnten wir das mal testen?

**Comment by afuerhoff** [comment]
Hallo, habe gerade einen Stand auf Github hochgeladen. Bitte testen

**Comment by iobFan** [comment]
Hi, habe es jetzt installiert und werde es ein paar Tage mit 10s testen. Gebe dir dann Rückmeldung, wie die Performance der FB ist. Danke dir schonmal :)

**Comment by iobFan** [comment]
Hallo @afuerhoff, ich habe mein Skript jetzt 2 Tage mit 10sek Intervall am laufen und konnte bisher keine Probleme feststellen. 👍🏻

Ich habe aktuell ca. 40 Devices im eigenen Netzwerk. Eigentlich benötige ich für meinen Use Case nur 1 Device. Macht es einen Unterschied, ob alle 40 Geräte alle 10 Sekunden abgefragt werden oder nur 1 Gerät? Falls ja. Ist es möglich, dass FB-Checkpresence nur Objekte für von mir definierte Geräte erstellt und abfragt?

**Comment by afuerhoff** [comment]
Hallo, das macht keinen Unterschied. Es werden immer ganze Listen von der Fritzbox gelesen.

Funktioniert denn dein Script so wie gewünscht? Was machst Du da genau?

**Comment by iobFan** [comment]
Danke für die Info :)

Ich habe mein WLAN über Mesh ziemlich stark ausgeweitet bis in den Garten (separates Grundstück). Da ich bisher immer nur nach active/inactive meine Alarmanlage getriggert habe, wurde diese nicht aktiviert, wenn ich im Gartengrundstück war. Dadurch dass ich jetzt erkennen kann, mit welchem Repeater ich verbunden bin, kann ich entsprechend meine Alarmanlage triggern. 

Ebenfalls öffnet ein Switchbot nun die Eingangstüre und die Alarmanlage wird deaktiviert, sobald ich mich mit dem Repeater in der Nähe der Haustüre verbinde (deshalb sind die 10 sekunden wichtig, da ich sonst lange warten muss). Dies passiert allerdings nur, wenn die Alarmanlage zuvor aktiv war.

**Comment by iobFan** [comment]
Hallo @afuerhoff,
seit dem letzten Update wird bei mir der Ordner "WLAN" nicht mehr aktualisiert. Ich habe diesen genutzt, um meine Alarm-Anlage zu aktivieren/deaktivieren, da ich hier den entsprechenden Repeater herausfinden konnte, mit dem mein Smartphone verbunden ist. 

Wäre cool, wenn die Änderung wieder rückgängig gemacht werden könnte.

Vielen Dank vorab :)

**Comment by iobFan** [comment]
Ich habe jetzt alle Objekte entfernt und neu eingelesen und es wird kein Unterordner innerhalb der Geräte namens "WLAN" angelegt. Die Datenpunkte im Ordner WLAN wurden zuletzt am 14.02. aktualisiert. Das hatte ich mir zuvor noch aufgeschrieben. Kann ich irgendwie prüfen, wann ich das Update von FB-Checkpresence installiert habe?

**Comment by iobFan** [comment]
Ok, ich sehe gerade, dass es genau am 14.02. gewesen sein muss. Files auf meinem RaspberryPi für fb-checkpresence wurden genau zu diesem Zeitpunkt aktualisiert, an denen die Daten unter WLAN nicht mehr aktualisiert wurden. 

Es muss aus meiner Sicht etwas mit dem Update zu tun haben.

**Comment by iobFan** [comment]
Hallo @afuerhoff, konntest du dir das Verhalten nochmal anschauen? Ich nutze Version 1.1.25 und seit der Installation wird der WLAN Ordner nicht mehr angelegt. Habe die FB Devices jetzt schon mehrfach neu eingelesen und Objekte zuvor gelöscht.

**Comment by afuerhoff** [comment]
Hab leider wenig Zeit im Moment. Bitte auf die alte Version zurück gehen.

**Comment by iobFan** [comment]
Danke dir. Ich habe es gerade getestet und es funktioniert leider auch nicht. Es sieht so aus, als ob Mesh nicht erkannt wird. Obwohl meine Fritzbox mit allen Repeatern im Mesh ist. 
Ich habe seit 2-3 Wochen die neue Fritz OS Version 7.50 installiert. Könnte es damit auch ggf. zusammenhängen?

**Comment by afuerhoff** [comment]
Ist das eine Beta Version?
Ansonsten die Repeater mal neu im Mesh  einbinden.

**Comment by iobFan** [comment]
Nein, ist die aktuelle Fritzbox Version für meine 6591 Cable. Danke, werde ich mal versuchen :)
