### ISSUE TITLE
FB Checkpresence sometimes not starting

### ISSUE THREAD

**Issue by iobFan** [afuerhoff/ioBroker.fb-checkpresence#126]
Hi @afuerhoff,
wenn ich meinen RaspberryPi neustarte, dann startet fb checkpresence nicht. Ich erhalte die unten genannten Fehler. Anschließend gebe ich das Passwort nochmal neu ein und starte den Adapter neu und dann klappt alles wieder. 

An was könnte dies liegen?  --> onReady: TypeError: Cannot read property 'val' of null

<html>
<body>

fb-checkpresence.0 | 2022-06-13 21:37:32.772 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
fb-checkpresence.0 | 2022-06-13 21:37:32.770 | info | terminating
host.raspberrypi | 2022-06-13 21:37:32.281 | info | stopInstance system.adapter.fb-checkpresence.0 send kill signal
fb-checkpresence.0 | 2022-06-13 21:37:32.269 | info | cleaned everything up ...
fb-checkpresence.0 | 2022-06-13 21:37:32.266 | info | Got terminate signal TERMINATE_YOURSELF
host.raspberrypi | 2022-06-13 21:37:32.211 | info | stopInstance system.adapter.fb-checkpresence.0 (force=false, process=true)
host.raspberrypi | 2022-06-13 21:37:32.209 | info | "system.adapter.fb-checkpresence.0" disabled
fb-checkpresence.0 | 2022-06-13 21:37:32.132 | warn | onReady: TypeError: Cannot read property 'val' of null
fb-checkpresence.0 | 2022-06-13 21:37:32.115 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2022-06-13 21:37:31.613 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.612 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.612 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.611 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.610 | info | X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.610 | info | X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.609 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.609 | info | WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.608 | info | WLANConfiguration3-GetInfo is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.608 | info | WLANConfiguration3-SetEnable is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.607 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.606 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.606 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.605 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.605 | info | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.604 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.604 | info | Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.603 | info | Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0 | 2022-06-13 21:37:31.602 | info | configuration default connection: 1.WANIPConnection.1
fb-checkpresence.0 | 2022-06-13 21:37:31.597 | info | start fb-checkpresence.0: FRITZ!Box 6591 Cable version: 161.07.29 ip-address: "fritz.box" - interval devices: 10 s - interval members: 60 s
fb-checkpresence.0 | 2022-06-13 21:37:30.850 | info | starting. Version 1.1.15 (non-npm: afuerhoff/ioBroker.fb-checkpresence) in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v14.19.3, js-controller: 4.0.23

</body>
</html>

**Comment by iobFan** [comment]
Hallo,
ich habe den History Adapter deaktiviert, da ich die Infos nicht nutze.

Der fb-checkpresence Adapter ist auf "3: Andere Adapter" eingestellt. Soll ich diesen früher starten?

**Comment by afuerhoff** [comment]
Der History Adapter muss früher starten als mein Adapter.
Ist aber ja bei dir dann nicht relevant. Dann muss ich weitersuchen.

**Comment by afuerhoff** [comment]
Kannst Du den History Adapter in der Konfiguration einmal einrichten und dann testen, ob der Fehler noch kommt.

**Comment by iobFan** [comment]
Kann ich auch meine influxdb als history adapter nehmen?

**Comment by iobFan** [comment]
Sieht gut aus. Bei einem ioBroker restart mit aktiviertem influxDB History Adapter startet der Adapter ohne Probleme.

**Comment by iobFan** [comment]
<html>
<body>


fb-checkpresence.0 | 2022-06-14 22:05:40.529 | info | loop successfully started
-- | -- | -- | --
fb-checkpresence.0 | 2022-06-14 22:05:40.527 | info | states successfully subscribed
fb-checkpresence.0 | 2022-06-14 22:05:40.525 | info | createFbDeviceObjects finished successfully
fb-checkpresence.0 | 2022-06-14 22:05:31.280 | warn | infoNoFamilyMembers: no family members defined! Objects are not created!
fb-checkpresence.0 | 2022-06-14 22:05:31.255 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2022-06-14 22:05:28.952 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.952 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.951 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.950 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.940 | info | X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.940 | info | X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.939 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.938 | info | WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.937 | info | WLANConfiguration3-GetInfo is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.937 | info | WLANConfiguration3-SetEnable is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.936 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.935 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.934 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.934 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.933 | info | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.932 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.931 | info | Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.910 | info | Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0 | 2022-06-14 22:05:28.909 | info | configuration default connection: 1.WANIPConnection.1
fb-checkpresence.0 | 2022-06-14 22:05:28.904 | info | start fb-checkpresence.0: FRITZ!Box 6591 Cable version: 161.07.29 ip-address: "fritz.box" - interval devices: 10 s - interval members: 60 s
fb-checkpresence.0 | 2022-06-14 22:05:27.566 | info | starting. Version 1.1.15 (non-npm: afuerhoff/ioBroker.fb-checkpresence) in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v14.19.3, js-controller: 4.0.23


</body>
</html>

**Comment by iobFan** [comment]
Könnte man das ggf. als info anstatt warning in Zukunft loggen? 

2022-06-14 22:05:31.280  - warn: fb-checkpresence.0 (13572) infoNoFamilyMembers: no family members defined! Objects are not created!

**Comment by iobFan** [comment]
Danke dir :) ich glaube ich hatte die github version für das intervall thema für meine repeater logik installiert. Werde wieder auf die latest switchen :) danke dir! Sehr cooler Adapter.

**Comment by afuerhoff** [comment]
Ich habe gerade eine neue Version auf Github hochgeladen. Kannst Du die noch einmal ohne konfigurierten History Adapter testen. Der Bug beim Neustart sollte dann hoffentlich Geschichte sein. Die Warnung sollte auch nicht mehr kommen sondern eine Info Meldung.

**Comment by iobFan** [comment]
Bin jetzt gerade leider unterwegs aber installiere es morgen Vormittag und melde mich dann. Schönen Abend dir.

**Comment by afuerhoff** [comment]
Ok. Dann kommt das dann in die 1.1.17.
