### ISSUE TITLE
Warnings in log with device list

### ISSUE THREAD

**Issue by OneCreek** [afuerhoff/ioBroker.fb-checkpresence#127]
**Describe the bug**  
Periodic warning in log about devicelist.

**To Reproduce**  
no problem with adapter 1.1.14. Now ioBroker Docker update and Adapter update and new Instance setup.

**Expected behavior**  

**Screenshots & Logfiles**  
`fb-checkpresence.0	2022-06-21 ...	warn	
devicelist: {"List":{"Item":[{"Index":"1","IPAddress":"","MACAddress":"B6:::::","Active":"0","HostName":"Blabla","InterfaceType":"","X_AVM-DE_Port":"0","X_AVM-DE_Speed":"0","X_AVM-DE_UpdateAvailable":"0","X_AVM-DE_UpdateSuccessful":"unknown","X_AVM-DE_InfoURL":"","X_AVM-DE_Model":"","X_AVM-DE_URL":"","X_AVM-DE_Guest":"0","X_AVM-DE_VPN":"0","X_AVM-DE_WANAccess":"error","X_AVM-DE_Disallow":"0"},`
und das für alle Index
Die warning passiert ungeführ jede Minute...

**Versions:**  
 - Adapter version: v1.1.17
 - JS-Controller version: 4.0.23
 - Node version: v16.15.1
 - NPM 8.11.0
 - Operating system: Raspberry buanet/iobroker:beta

**Additional context**  
no problem with adapter 1.1.14. Now ioBroker Docker update and Adapter update and new Instance setup.

**Comment by OneCreek** [comment]
yes. Downloaded yesterday after many issues in the log after ioBroker update.

**Comment by afuerhoff** [comment]
Please install from the official repositories.  Github is only for testing or debuging.

**Comment by OneCreek** [comment]
Ok, actually after resetting everything and using the latest official one, no issues so far. Thanks and sorry for raising this issue.

**Comment by OneCreek** [comment]
Ok, actually after resetting everything and using the latest official one, no issues so far. Thanks and sorry for raising this issue.
