### ISSUE TITLE
[Idee] presence name

### ISSUE THREAD

**Issue by adcrafter27** [afuerhoff/ioBroker.fb-checkpresence#13]
Hallo, erstmal danke für den guten Adapter er funktioniert bei mir sehr gut.

es gibt ja den punkt presence der ja besagt das min 1 Familien Mittelglied anwesend ist
gut währe es wenn es noch einen "presence-name" wert geben würde um schneller festzustellen wer online ist (nur der name)  ohne das man alle einzeln abfragen müsste zbs bei größeren Familien mit Kindern

Das selbe währe auch noch in umgekehrter Reihenfolge gut
presenceAll besagt ja das alle da sind, wenn false könnte man sagen wer nicht hier ist
das würde bei einer Visualisierung und Telegramm Benachrichtigung einiges erleichtern

**Comment by afuerhoff** [comment]
In welcher Art und Weise sollen die Namen denn gespeichert werden? Als Json Tabelle oder einfach als Text mit Komma getrennt?

**Comment by adcrafter27** [comment]
Schön das du dich der Sache annehmen möchtest.
Wenn man sie einfach mit Komma trennt, könnte man den "wert" einfach übernehmen in Telegram.
Eine Weiterverarbeitung währe auch noch einfach möglich da man die einzelnen namen durch das Komma splitten könnte

**Comment by afuerhoff** [comment]
Ist in Version 1.0.0 eingebaut
