### ISSUE TITLE
At add-familymemebers list always empty

### ISSUE THREAD

**Issue by WolfgangN57** [afuerhoff/ioBroker.fb-checkpresence#138]
To add a family-member I click the button, but list is empty.
When I changed user and pw list ist doubled and hardly readable.
Then I checked a few devices but when add-button is pushed nothing is added to the list
adapter version is 1.1.19
 and it connects to fritzbox
adapterlog is on debug and gives the following warnings:

fb-checkpresence.0 | 2022-07-26 17:25:59.469 | warn | getActive Wolfgangs-iPhone: Error: The feature hostname is not supported for Wolfgangs-iPhone!
fb-checkpresence.0 | 2022-07-26 17:25:59.468 | warn | getActive iPhonevonSabine: Error: The feature hostname is not supported for iPhonevonSabine!
fb-checkpresence.0 | 2022-07-26 17:25:49.580 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2022-07-26 17:25:49.580 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2022-07-26 17:25:49.580 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2022-07-26 17:25:49.579 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2022-07-26 17:25:49.577 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2022-07-26 17:25:49.576 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2022-07-26 17:25:49.487 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.487 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.486 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.486 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.486 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.485 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.485 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.484 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.484 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.483 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.483 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.482 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.482 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.481 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.481 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.480 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-26 17:25:49.117 | warn | please check the user or password!

**Comment by afuerhoff** [comment]
Hello, has you set correctly the user and password in the configuration?

**Comment by WolfgangN57** [comment]
Yes, I have 3 users and each time I tested with different users (they have full rights) then I have a list, but it is overdubbed two times, so it is hard to select a device. But if a device is selected and the add-button is pressed, the device is not added to the list.

**Comment by WolfgangN57** [comment]
and then after restart of adapter the list is empty again

**Comment by WolfgangN57** [comment]
![IMG_1196](https://user-images.githubusercontent.com/67851947/181079005-98540442-7417-435d-99dc-595f2fb66020.jpg)
![IMG_1197](https://user-images.githubusercontent.com/67851947/181079032-1903d8fa-1098-481c-9d2d-0091a28e7142.jpg)

**Comment by afuerhoff** [comment]
Can you post the log from start of adapter up to the first loop. I need not only the warnings.

PS: In your first log, there was following entry: fb-checkpresence.0 | 2022-07-26 17:25:49.117 | warn | please check the user or password! -> The adapter runs not correctly. Most of the features were deactivated.

**Comment by WolfgangN57** [comment]
about the user/pw message:
I entered it correctly, then, when I want to add a familymemeber, the list is not empty but overlaid double. The I try to select some devices and click add. None of the selected devices was added to the family. Then when I want to do this a second time, the list is empty. When I now take another user of the fritzbox, the game starts again.
A reinstall did not solve the problem.
Here is the log:

fb-checkpresence.0 | 2022-07-27 15:58:46.411 | debug | loop main ends after 0,112395970 s
-- | -- | -- | --
fb-checkpresence.0 | 2022-07-27 15:58:44.296 | debug | loop family ends after 0,18841176 s
fb-checkpresence.0 | 2022-07-27 15:58:44.288 | warn | getActive Galaxy-J5: Error: The feature hostname is not supported for Galaxy-J5!
fb-checkpresence.0 | 2022-07-27 15:58:44.287 | warn | getActive iPhone-von-Lina: Error: The feature hostname is not supported for iPhone-von-Lina!
fb-checkpresence.0 | 2022-07-27 15:58:44.287 | warn | getActive Galaxy-A51-pol-zovatela-Arsenii: Error: The feature hostname is not supported for Galaxy-A51-pol-zovatela-Arsenii!
fb-checkpresence.0 | 2022-07-27 15:58:44.286 | warn | getActive DESKTOP-I9VELQ6: Error: The feature hostname is not supported for DESKTOP-I9VELQ6!
fb-checkpresence.0 | 2022-07-27 15:58:44.286 | warn | getActive Theresa-iPhone-XS: Error: The feature hostname is not supported for Theresa-iPhone-XS!
fb-checkpresence.0 | 2022-07-27 15:58:44.285 | warn | getActive EmmasIphone: Error: The feature hostname is not supported for EmmasIphone!
fb-checkpresence.0 | 2022-07-27 15:58:44.284 | warn | getActive Justins-Iphone: Error: The feature hostname is not supported for Justins-Iphone!
fb-checkpresence.0 | 2022-07-27 15:58:44.284 | warn | getActive HUAWEI-P-smart-f113973a85: Error: The feature hostname is not supported for HUAWEI-P-smart-f113973a85!
fb-checkpresence.0 | 2022-07-27 15:58:44.283 | warn | getActive DESKTOP-9SMBJ98: Error: The feature hostname is not supported for DESKTOP-9SMBJ98!
fb-checkpresence.0 | 2022-07-27 15:58:44.282 | warn | getActive Wolfgangs-iPhone: Error: The feature hostname is not supported for Wolfgangs-iPhone!
fb-checkpresence.0 | 2022-07-27 15:58:44.281 | warn | getActive iPhonevonSabine: Error: The feature hostname is not supported for iPhonevonSabine!
fb-checkpresence.0 | 2022-07-27 15:58:43.276 | info | loop successfully started
fb-checkpresence.0 | 2022-07-27 15:58:43.275 | info | states successfully subscribed
fb-checkpresence.0 | 2022-07-27 15:58:43.275 | info | createMemberObjects finished successfully
fb-checkpresence.0 | 2022-07-27 15:58:40.822 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2022-07-27 15:58:40.191 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.191 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.190 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.190 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.189 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.189 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.189 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.188 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.188 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.187 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.187 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.187 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.186 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.186 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2022-07-27 15:58:40.186 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.186 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2022-07-27 15:58:40.185 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.185 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2022-07-27 15:58:40.185 | info | configuration default connection: -
fb-checkpresence.0 | 2022-07-27 15:58:40.184 | debug | configuration filter delay: 15
fb-checkpresence.0 | 2022-07-27 15:58:40.184 | debug | configuration external ip address: true
fb-checkpresence.0 | 2022-07-27 15:58:40.184 | debug | configuration guest info: true
fb-checkpresence.0 | 2022-07-27 15:58:40.183 | debug | configuration qr code: false
fb-checkpresence.0 | 2022-07-27 15:58:40.183 | debug | configuration ssl: true
fb-checkpresence.0 | 2022-07-27 15:58:40.182 | debug | configuration compatibility: false
fb-checkpresence.0 | 2022-07-27 15:58:40.182 | debug | configuration whitelist: false
fb-checkpresence.0 | 2022-07-27 15:58:40.181 | debug | configuration mesh info: true
fb-checkpresence.0 | 2022-07-27 15:58:40.181 | debug | configuration fb-devices true
fb-checkpresence.0 | 2022-07-27 15:58:40.180 | debug | configuration familymembers: [{"enabled":true,"group":"Familie","familymember":"iPhonevonSabine","devicename":"iPhonevonSabine","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Sabine"},{"enabled":true,"group":"Familie","familymember":"Wolfgangs-iPhone","devicename":"Wolfgangs-iPhone","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Wolfgang"},{"enabled":true,"group":"Gast","familymember":"DESKTOP-9SMBJ98","devicename":"DESKTOP-9SMBJ98","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Natasha"},{"enabled":true,"group":"Gast","familymember":"HUAWEI-P-smart-f113973a85","devicename":"HUAWEI-P-smart-f113973a85","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Natasha"},{"enabled":true,"group":"Familie","familymember":"Justins-Iphone","devicename":"Justins-Iphone","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Justin"},{"enabled":true,"group":"Familie","familymember":"EmmasIphone","devicename":"EmmasIphone","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Emma"},{"enabled":true,"group":"Familie","familymember":"Theresa-iPhone-XS","devicename":"Theresa-iPhone-XS","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Theresa"},{"enabled":true,"group":"Gast","familymember":"DESKTOP-I9VELQ6","devicename":"DESKTOP-I9VELQ6","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Natasha"},{"enabled":true,"group":"Gast","familymember":"Galaxy-A51-pol-zovatela-Arsenii","devicename":"Galaxy-A51-pol-zovatela-Arsenii","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Arsenii"},{"enabled":true,"group":"Gast","familymember":"iPhone-von-Lina","devicename":"iPhone-von-Lina","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Lina"},{"enabled":true,"group":"Gast","familymember":"Galaxy-J5","devicename":"Galaxy-J5","macaddress":"","ipaddress":"","usage":"Hostname","usefilter":true,"comment":"Sascha"}]
fb-checkpresence.0 | 2022-07-27 15:58:40.180 | debug | configuration familymembers count: 11
fb-checkpresence.0 | 2022-07-27 15:58:40.180 | debug | configuration dateformat: <yyyy.mm.dd HH:MM:ss>
fb-checkpresence.0 | 2022-07-27 15:58:40.179 | debug | configuration history: <history.0>
fb-checkpresence.0 | 2022-07-27 15:58:40.178 | debug | configuration user: <fritz6272>
fb-checkpresence.0 | 2022-07-27 15:58:40.177 | info | start fb-checkpresence.0: FRITZ!Box 6690 Cable version: 267.07.29 ip-address: "192.168.0.254" - interval devices: 60 s - interval members: 60 s
fb-checkpresence.0 | 2022-07-27 15:58:39.879 | warn | please check the user or password!
fb-checkpresence.0 | 2022-07-27 15:58:39.569 | info | starting. Version 1.1.19 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v16.16.0, js-controller: 4.0.23
fb-checkpresence.0 | 2022-07-27 15:58:38.838 | debug | States connected to redis: 192.168.0.152:9000
fb-checkpresence.0 | 2022-07-27 15:58:38.730 | debug | States create User PubSub Client
fb-checkpresence.0 | 2022-07-27 15:58:38.728 | debug | States create System PubSub Client
fb-checkpresence.0 | 2022-07-27 15:58:38.667 | debug | Redis States: Use Redis connection: 192.168.0.152:9000
fb-checkpresence.0 | 2022-07-27 15:58:38.566 | debug | Objects connected to redis: 192.168.0.152:9001
fb-checkpresence.0 | 2022-07-27 15:58:38.557 | debug | Objects client initialize lua scripts
fb-checkpresence.0 | 2022-07-27 15:58:38.348 | debug | Objects create User PubSub Client
fb-checkpresence.0 | 2022-07-27 15:58:38.346 | debug | Objects create System PubSub Client
fb-checkpresence.0 | 2022-07-27 15:58:38.342 | debug | Objects client ready ... initialize now
fb-checkpresence.0 | 2022-07-27 15:58:38.229 | debug | Redis Objects: Use Redis connection: 192.168.0.152:9001
fb-checkpresence.0 | 2022-07-27 15:57:44.824 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2022-07-27 15:57:44.822 | info | terminating
fb-checkpresence.0 | 2022-07-27 15:57:44.320 | info | cleaned everything up ...
fb-checkpresence.0 | 2022-07-27 15:57:44.318 | info | Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.0 | 2022-07-27 15:57:18.615 | debug | loop main ends after 0,110196065 s
fb-checkpresence.0 | 2022-07-27 15:57:16.502 | debug | loop family ends after 0,1319224 s

**Comment by afuerhoff** [comment]
The log says, that you have a configuration problem. Most of the functions were deactivated. Please check the adapter configuration (user and pw) and the fritzbox user configuration. Are there any special characters in the password? Could be that the user have not the full rights. Some times also helps a fritzbox reboot.

**Comment by WolfgangN57** [comment]
Reboot performed, no change
Username and pw must be correct, otherwise i dont get any list at first try, at second try list is empty and log gives warn about user/pw, strange

**Comment by WolfgangN57** [comment]
Users have full rights

**Comment by afuerhoff** [comment]
Here I see no user in the log:
![image](https://user-images.githubusercontent.com/50245893/181346780-dfc113ff-7104-42f1-aa7a-0fea813338c2.png)

**Comment by afuerhoff** [comment]
Which admin adapter did you install? With the 6.2.3 I also have the problems whith the doubled dialog box.

**Comment by afuerhoff** [comment]
When you have the error "please check the user or password!" then clear the password and edit it again. The encryption of password function in the admin adapter have also problems.
see also here: https://github.com/ioBroker/ioBroker.admin/issues/1598
If this not helps, please install the stable version of admin adapter.

**Comment by WolfgangN57** [comment]
admin is 6.2.4, will try the stable one

**Comment by WolfgangN57** [comment]
with admin 5.3.8 everything fine again
Thanks for the help

**Comment by afuerhoff** [comment]
The next version has a workaround that the admin adapter error has no more an impact.
