### ISSUE TITLE
Not working with FB Version 7.39

### ISSUE THREAD

**Issue by muellerjm** [afuerhoff/ioBroker.fb-checkpresence#143]
Addon ist not working with actual Laborversion 7.39. The status does not change

**Comment by afuerhoff** [comment]
Without a log I can say nothing. Please switch to log level debug and post it. Before you should do that stop the adapter and reboot the fritzbox.Have you a stable admin or a beta one?

**Comment by muellerjm** [comment]
Since iobroker is live, I had to go back to the official version and I can't test any further.  Please keep it as a reminder. Thank you very much.
