### ISSUE TITLE
Presence does not work when the device is connected via ethernet

### ISSUE THREAD

**Issue by Culinator** [afuerhoff/ioBroker.fb-checkpresence#15]
So i had the idea to automate something when switch my pc on. I create a new familymember and so on. But the problem is that my PC is always "presence" even when disonnected or switched off. So i looked into my fritzbox and found the problem. Even here the PC was listed under active devices. 

But there was a difference. In my FritzBox i can see the data rate of the PC when it's connected and the data rate is not shown when its disconnected. Unfortunately this information cannot be viewed in the tool.

So my question is, if you can add the information (if available) to your tool.

 - Adapter version: 0.3.0
 - JS-Controller version: 4.3.4
 - Node version: 12.16.1
 - Operating system: raspery pi

**Comment by afuerhoff** [comment]
Hi, I have added a new Version released on Github. I have added the speed State under the fbdevices. After installation you should insert the password again and save the configuration. Please check, if the New version can solve your problem.

**Comment by Culinator** [comment]
Hey, thank you very much. I installed the Github version and the speed state is now available. Until now i dont tested it, but there should be no problems now.

By the way its a realy cool adapter, which makes it much more easier for me to make my home realy smart :)
