### ISSUE TITLE
Adapter wird Terminated in Version 1.1.21

### ISSUE THREAD

**Issue by peoples0815** [afuerhoff/ioBroker.fb-checkpresence#159]
Ich habe eben mal die Git-Version installiert und nach dem Update startet der Adapter kurz und geht wieder aus mit folgender Meldung im Log: onReady: Fb init: TypeError: Cannot read properties of undefined (reading 'source')

1.1.19 funktioniert tadelos.

**Comment by afuerhoff** [comment]
Die Version auf Github ist nicht für den normalen Gebrauch zugelassenen. Nur nach Aufforderung durch mich zum Testen. Bitte wieder die Version aus dem offiziellen Repository verwenden.

**Comment by afuerhoff** [comment]
Kein Fehler, da ein Entwicklungsstand.
