### ISSUE TITLE
No history before this day

### ISSUE THREAD

**Issue by daniel-lo** [afuerhoff/ioBroker.fb-checkpresence#16]
Hi .. I restored my installation on another machine .. now I get loads of messages like this in the log file:

(1143) <device name>: No history before this day is available (lastVal = null)

**Comment by afuerhoff** [comment]
Die Meldung verschwindet nach einem Tag. Der Adapter benötigt mindestens einen Eintrag vom Vortag.

**Comment by daniel-lo** [comment]
nice .. thx

**Comment by daniel-lo** [comment]
ist noch da

**Comment by afuerhoff** [comment]
Which adapter version is installed?

**Comment by daniel-lo** [comment]
1.0.1

**Comment by afuerhoff** [comment]
Which history adapter is configured in the adapter settings? Is the history enabled for every family member?  A logfile is usefull. Please set the loglevel to debug.

**Comment by daniel-lo** [comment]
history.0 .. but I only added members and activated them .. do I have to tick something else for history to be used?

**Comment by afuerhoff** [comment]
No. In the object tab for every member  the history should be enabled over the adapter. I think I need the log.

**Comment by daniel-lo** [comment]
the root object of each device has history active .. I will set to debug

**Comment by daniel-lo** [comment]
https://privatebin.net/?beddc149cb589181#5wGQEaYibYSZ768PyXPQWU1GfyBke4G7s8Uohv4pjRH4

**Comment by afuerhoff** [comment]
Hello, 
can you give me the history settings from one device? Are there more than one day listed in the history table view? In the log I can't see only one day.

**Comment by daniel-lo** [comment]
Settings
![hist](https://user-images.githubusercontent.com/4311558/80628249-5fa73880-8a51-11ea-9e2e-657059793607.png)

**Comment by daniel-lo** [comment]
I have no idea where the history table view is.

**Comment by afuerhoff** [comment]
Next to settings

![image](https://user-images.githubusercontent.com/50245893/80629504-39829800-8a53-11ea-99cf-ac79963af68a.png)

**Comment by daniel-lo** [comment]
![table](https://user-images.githubusercontent.com/4311558/80631046-75b6f800-8a55-11ea-9036-0813c85beb72.png)

**Comment by afuerhoff** [comment]
Are there only values from 2020-04-29?

**Comment by daniel-lo** [comment]
yes .. that's all there is

**Comment by afuerhoff** [comment]
This is the problem. The adapter needs minimum one value from the day before.

**Comment by daniel-lo** [comment]
so .. what shall I do? I didn't configure anything

**Comment by afuerhoff** [comment]
You should wait. Tomorrow you have the values from the day before.

**Comment by daniel-lo** [comment]
Hmm .. see when the thread started? 3 days ago.

**Comment by afuerhoff** [comment]
Yes, but the history have no values from the 28 of April. When no State changes you have no values in the history. Have you deleted the objects?

**Comment by daniel-lo** [comment]
I didn't delete anything .. but maybe it's a good idea to delete the objects .. could be they failed to be restored from the backup. And all objects are constantly moving so presence should be updated.

**Comment by daniel-lo** [comment]
deleted the objects .. I guess now I'll have to wait another day to report

**Comment by afuerhoff** [comment]
Before you deleted the objects and restart the adapter, have you the message again in the log today? The history messages in the log should have history items from two days.

You should have a look in the history tab. If there are items from 2 days, then all should be correct.

**Comment by daniel-lo** [comment]
I cannot tell .. I had a some adapters that didn't work and had to downgrade node/nodejs (now they work) .. and I deleted the objects from your adapter. So currently history only has entries from today .. I will have to wait till tomorrow.

**Comment by daniel-lo** [comment]
No entry at all this morning .. but I checked .. it records (turned off wifi for a moment) .. I wonder if this is good or not .. I think all devices were present all the time. So I will need more time to observe. Anyway I wanted to ask .. why does the adapter need a historical entry? Just for education.

**Comment by afuerhoff** [comment]
I need minimum one value true or false from the days before, because I calculate the absent and present time values from 00:00 to 23:59 based on this value. It is the start value for calculation. 
I think about a change in this behaviour to prevent this messages direct after installation without history values. But it is important for the function to have this history values. In the log the adapter listed (with log level debug) the history values from the present day and one value from the days before. If not, you can check in the history adapter the values in the table tab, if there are more than one day recorded. If there are more than one day and message pop up then it is an error.

**Comment by afuerhoff** [comment]
The error is commented in the iobroker forum.

[ioBroker Forum](https://forum.iobroker.net/topic/31787/test-adapter-fb-checkpresence-v1-0-x/84)

**Comment by daniel-lo** [comment]
thx .. I am not aware of having network problems .. strange

**Comment by daniel-lo** [comment]
happens a lot:


fb-checkpresence.0 | 2020-05-02 12:18:44.546 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
-- | -- | -- | --
fb-checkpresence.0 | 2020-05-02 11:27:45.025 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 11:26:44.735 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 11:14:44.364 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:55:44.472 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:52:44.589 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:43:44.361 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:39:44.427 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:30:45.742 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 10:08:44.672 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 09:29:44.432 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 09:28:45.096 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded
fb-checkpresence.0 | 2020-05-02 08:59:44.359 | error | (1816) Fb.getDeviceList Error: timeout of 2000ms exceeded

**Comment by Ilovegym66** [comment]
looks like fixed with 1.0.2 :-)

**Comment by afuerhoff** [comment]
Issue is fixed with version 1.0.2.
