### ISSUE TITLE
checkDevices: getMeshList: AxiosError: timeout of 14000ms exceeded

### ISSUE THREAD

**Issue by esusxunil** [afuerhoff/ioBroker.fb-checkpresence#167]
Hello together,

from time to time (4-5 times a day) I get the following error message:

checkDevices: getMeshList: AxiosError: timeout of 14000ms exceeded

Version is the last one from the official repository 1.1.19 
Other than that the adapter seems to work correctly.

**Comment by afuerhoff** [comment]
Hello, its a problem of the connection to the router. 
I cannot change this behaviour. Do you have a huge network?

**Comment by esusxunil** [comment]
Yes, indeed, around 80 clients (2/3 IoT) and several Repeaters in LAN Bridge Mode.

But okay, then I will just decrease the Protokoll level to error. Everything else is working fine, thanks for the adapter.

**Comment by afuerhoff** [comment]
Nothing changed
