### ISSUE TITLE
Adapter is not starting

### ISSUE THREAD

**Issue by Sandomor** [afuerhoff/ioBroker.fb-checkpresence#175]
in the Error log i can find 
"onReady: Fb init: ReferenceError: AbortController is not defined"

whats wrong?

(Ver 1.1.23)

**Comment by Sandomor** [comment]
Vers. 1.1.19 is still working (installed the Vers. 1.1.19)

**Comment by afuerhoff** [comment]
The new Function AbortController needs Node 16. Which Version do you use?

**Comment by afuerhoff** [comment]
I have uploaded a new test version on github. Please test it.

**Comment by Sandomor** [comment]
Thx for the help - i'd have node 14 installed - since i updated to 16 (this morning) Vers 1.1.23 is working now too - thx
