### ISSUE TITLE
warning: duplicate hostname

### ISSUE THREAD

**Issue by Ilovegym66** [afuerhoff/ioBroker.fb-checkpresence#18]
after every start of the adapter, the warning "duplicate hostname device macaddress" is show in the logfile. 
Sorry, thats normal, because a lot of devices must HAVE more network adapters and mac addresses... :-)
A Server have one Hostname, and 2 LAN devices and a wifi device, so it's not possible to change to every Mac Address the hostname.
Disable this warning, please, make no sense..

`
fb-checkpresence.0 | 2020-05-04 13:36:27.397 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Diskstation 00:11:32:A6:75:70
-- | -- | -- | --
fb-checkpresence.0 | 2020-05-04 13:36:27.396 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Diskstation 00:11:32:A6:75:6F
fb-checkpresence.0 | 2020-05-04 13:36:27.394 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Android-5 8C:45:00:A8:75:83
fb-checkpresence.0 | 2020-05-04 13:36:27.394 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Android-5 6C:56:97:54:C2:A2
fb-checkpresence.0 | 2020-05-04 13:36:27.393 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Android-2 58:B1:0F:01:A7:2E
fb-checkpresence.0 | 2020-05-04 13:36:27.393 | warn | (12616) dublicate fritzbox device item. Please correct the hostname in  the fritzbox settings for the device -> Android-2 20:47:DA:01:7B:93

`

**Comment by FRYYYYYY** [comment]
Yes, same here:
![image](https://user-images.githubusercontent.com/13643787/81420164-d3cb9580-914f-11ea-9614-e34f535119a1.png)

Sometimes I am connecting via WLAN, sometimes via the dock.

PS: "Duplicate" is spelled with a "p," not a "b."

**Comment by Ilovegym66** [comment]
fixed with 1.0.2
