### ISSUE TITLE
since FritzOS 7.50 I get warnings "getAllFbObjects: Hostname of fritzbox device ... is empty!"

### ISSUE THREAD

**Issue by Diginix** [afuerhoff/ioBroker.fb-checkpresence#180]
Since FritzBox firmware update to FRITZ!OS-Version 7.50, I get every minute this log warnings:
`fb-checkpresence.0 | 2023-01-20 07:23:04.795 | warn | getAllFbObjects: Hostname of fritzbox device A2:D7:0B:08:89:A7 is empty!`
This MAC was 2 days ago shortly connected to guest wifi. Since then it isn't there and even not listed in Fritzbox.
But as it seems the adapter retrieves this continuously forever.

adapter: 1.1.24
nodejs: 16.19.0
js-controller: 4.0.24

**Comment by afuerhoff** [comment]
The problem is that the input from fritzbox has an empty hostname. Without a hostname the adapter cannot work with the data correctly.  That seems to be a fritzbox problem. I will check this.

**Comment by Diginix** [comment]
So far so clear. But strange that the pulled list still contains this devices, that are away since days.
And nowhere are shown in FritzOS. So it isn't possible for me to "reset" this device by removing it from the known devices list in FritzOS.

**Comment by afuerhoff** [comment]
When I logged in as a guest and then logged of than my device is listed as inactive in the fritzbox. Version 7.29 fritzbox 7490.

**Comment by Diginix** [comment]
My FB runs now with FritzOS 7.50 and I saw the MAC for a short time in the list, but as incomplete device and it wasn't removable. After a refresh of the device list it was gone. But the adapter still gets it over the API. I run it now with log level error.
Don't know whether a reboot of the Fritzbox would help to stop the warn messages. But I won't reboot it yet.

**Comment by afuerhoff** [comment]
You can try to add the same mac with an ip and a hostname in the fritzbox. And than you can delete the device.

**Comment by Diginix** [comment]
You can't add a manual device with an IP from guest network. I have tried to add the MAC with an IP from the main network. But the device appears only some seconds in the list. To short to be able to delete it.

I have checked my history of fb-checkpresence.0.guest.listJson and I saw that the time when the guest device was connected it had a hostname and IP:
```
{
    "Hostname": "PC-A2-D7-0B-08-89-A7",
    "IP-Address": "192.168.179.4",
    "MAC-Address": "A2:D7:0B:08:89:A7",
    "disabled": "false"
}
```
But after disconnecting, the FB seems to deliver it farther without all values.

**Comment by afuerhoff** [comment]
I have uploaded a test version on github. With this the warning should come only once. Please test it and give feedback. When it works for you than I will release this in a new version.

**Comment by Diginix** [comment]
I have rebooted now the FB and after that I saw my manual created device with that MAC and it had a hostname. Then I was able to delete it and now the instance doesn't brings warings in log. So for the moment I can't test the new version, but nethertheless it would be good to prevent log spamming with such problems.
