### ISSUE TITLE
Fritte Version: 7.50 Mash über Repeater Fehler

### ISSUE THREAD

**Issue by Mephisto090** [afuerhoff/ioBroker.fb-checkpresence#185]
Hej,

ich habe die fritte 7530 und den Repeater 2400. Irgendwie werden in der Masterbox keine Geräte mehr angezeigt die mit dem Repeater verbunden sind. Somit werden Geräte die zwar Zuhause sind und mit dem Repeater verbunden sind nicht mehr als anwesend geführt, nur wenn sie sich mit der Mainfritte verbinden.

![image](https://user-images.githubusercontent.com/85995176/216118117-e1e5a13f-5287-43cb-a10d-4801029abca8.png)

VG

**Comment by afuerhoff** [comment]
Der Repeater ist aber nicht im Mesh eingebunden.

**Comment by Mephisto090** [comment]
Wie meinst du das?

**Comment by afuerhoff** [comment]
Am Repeater Symbol müsste dann das Mesh Zeichen angezeigt werden
![image](https://user-images.githubusercontent.com/50245893/216129053-c953148e-11b2-4893-af98-a37426b007d5.png)
https://avm.de/mesh/faqs/fritzrepeater-im-mesh-einrichten/

**Comment by Mephisto090** [comment]
wie kann ich das ändern?

**Comment by afuerhoff** [comment]
Dafür hatte ich die URL eingefügt.

**Comment by afuerhoff** [comment]
Sie ist jedenfalls nicht richtig eingebunden worden und damit hast Du auch nicht die Vorteile eines Mesh-Netzwerks.

**Comment by Mephisto090** [comment]
Jetzt passt es danke
