### ISSUE TITLE
No Devices in 2nd instance

### ISSUE THREAD

**Issue by thomke67** [afuerhoff/ioBroker.fb-checkpresence#186]
Hi there,

I added a second instance.
This one is connected to a second FritzBox (it is a 7330 SL). The box is installed as a LAN bridge to the first box and is not connected via Mesh. When I open the Fritzbox interface I am able to see some connected devices.
The FB presence instance connects to the box without any issues.
But when I try to  add family members I do not see them (see screenshot 1).
So I added the by hand (Name, IP, MAC).
But now I got some error messages in the log and also I got a total different object tree than with the first instance (see screenshot 2). Some warnings in the log as well that some DP will not be updated in the future.

Has somebody any ideas how to fix that?

Regards,
Thomas

![grafik](https://user-images.githubusercontent.com/57798896/216820388-3af5a3d0-798b-4d2c-88ae-66796c4cb8b6.png)

![grafik](https://user-images.githubusercontent.com/57798896/216820685-78a740d8-35d2-458c-a693-283fecc69ca9.png)

**Comment by afuerhoff** [comment]
Was für eine Firmware läuft auf der Fritzbox? Da dürften einige Meldungen im Log sein beim Start des Adapters.

**Comment by thomke67** [comment]
Hallo,

hier der Log beim Start von der 2. Instanz:
`<html><body>


fb-checkpresence.1 | 2023-02-06 13:02:19.689 | warn | getActive  Nils:  Hosts:1 GetSpecificHostEntry: NoSuchEntryInArray -> please  check entry (mac, ip, hostname) in configuration! It is not listed in  the Fritzbox device list
-- | -- | -- | --
fb-checkpresence.1 | 2023-02-06 13:02:17.836 | info | loop successfully started
fb-checkpresence.1 | 2023-02-06 13:02:17.834 | info | states successfully subscribed
fb-checkpresence.1 | 2023-02-06 13:02:17.833 | info | createMemberObjects finished successfully
fb-checkpresence.1 | 2023-02-06 13:02:17.686 | warn | The  state "fb-checkpresence.1.Andrea" will not longer exist in a future  version. Please use fb-checkpresence.1.Andrea.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:17.569 | warn | The  state "fb-checkpresence.1.Thomas" will not longer exist in a future  version. Please use fb-checkpresence.1.Thomas.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:17.407 | warn | The  state "fb-checkpresence.1.Lars" will not longer exist in a future  version. Please use fb-checkpresence.1.Lars.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:17.282 | warn | The  state "fb-checkpresence.1.Nils" will not longer exist in a future  version. Please use fb-checkpresence.1.Nils.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:17.110 | info | createGlobalObjects finished successfully
fb-checkpresence.1 | 2023-02-06 13:02:16.619 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.1 | 2023-02-06 13:02:16.619 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.1 | 2023-02-06 13:02:16.619 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:16.618 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.1 | 2023-02-06 13:02:16.616 | warn | You should then manually delete the old states!
fb-checkpresence.1 | 2023-02-06 13:02:16.615 | warn | In  an future version some states are not more existent. Please use  compatibility = false to switch to the new handling of the states!
fb-checkpresence.1 | 2023-02-06 13:02:16.593 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.593 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.592 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.592 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.592 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.592 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.591 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.591 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.590 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.590 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-06 13:02:16.589 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.1 | 2023-02-06 13:02:16.588 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-06 13:02:16.588 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-06 13:02:16.587 | info | configuration default connection: 1.WANIPConnection.1
fb-checkpresence.1 | 2023-02-06 13:02:16.583 | info | start  fb-checkpresence.1: FRITZ!Box 7330 SL (UI) version: not defined  ip-address: "xxx.xxx.xxx.xxx" - interval devices: 10 s - interval members:  10 s
fb-checkpresence.1 | 2023-02-06 13:02:16.433 | info | service X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-06 13:02:16.432 | info | service X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-06 13:02:16.416 | info | service WLANConfiguration3-GetSecurityKeys is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-06 13:02:16.415 | info | service WLANConfiguration3-GetInfo is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-06 13:02:16.414 | info | service WLANConfiguration3-SetEnable is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-06 13:02:15.310 | info | starting. Version 1.1.20 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v16.19.0, js-controller: 4.0.24


</body>
</html>`

Auf der 7590 läuft FritzOS 7.50 und azf der 7330 läuft 6.55.

Gruß,
Thomas

**Comment by afuerhoff** [comment]
Die Firmware 6.55 unterstützt nur wenige Services, wie du im Log sehen kannst. Die ist sehr alt. Die Liste der Devices kann z.B. nicht ausgelesen werden -> Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated.

Ein Familienmitglied kann nur per Mac Adresse abgerufen werden. Hostname und IP funktionieren nicht.

**Comment by thomke67** [comment]
Die Familienmitglieder rufe ich auch per MAC ab. Wenn ich Hostname und IP rausnehme, habe ich dann weniger Fehlermeldungen?
Leider gibt es für die Box keine neuere Firmware....

**Comment by afuerhoff** [comment]
Das bringt nichts. Die Firmware ist zu alt.

Die Meldung deutet aber daraufhin, dass du die IP nutzt.
-> getActive Nils: Hosts:1 GetSpecificHostEntry: NoSuchEntryInArray -> please check entry (mac, ip, hostname) in configuration! It is not listed in the Fritzbox device list
Bitte in der Konfiguration prüfen.

**Comment by thomke67** [comment]
Ich nutze alle drei (mac, ip, hostname) und Nils wird auch erkannt, aber die Fehlermeldungen nerven mich.......

**Comment by afuerhoff** [comment]
Alle drei kannst du nicht nutzen. Es gibt die Einstellung
"Benutzung von". Mit der wählt man aus, ob die Mac, IP oder der Hostname ausgewertet wird. Mit der alten Firmware muss es auf Mac stehen.

**Comment by thomke67** [comment]
Steht und stand auf MAC. Nun habe ich den Rest gelöscht und es sind deutich weniger Meldungen:

<html><body>


fb-checkpresence.1 | 2023-02-08 19:11:22.228 | warn | getActive  Nils:  Hosts:1 GetSpecificHostEntry: NoSuchEntryInArray -> please  check entry (mac, ip, hostname) in configuration! It is not listed in  the Fritzbox device list
-- | -- | -- | --
fb-checkpresence.1 | 2023-02-08 19:11:20.396 | info | loop successfully started
fb-checkpresence.1 | 2023-02-08 19:11:20.395 | info | states successfully subscribed
fb-checkpresence.1 | 2023-02-08 19:11:20.393 | info | createMemberObjects finished successfully
fb-checkpresence.1 | 2023-02-08 19:11:20.196 | warn | The  state "fb-checkpresence.1.Andrea" will not longer exist in a future  version. Please use fb-checkpresence.1.Andrea.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:19.973 | warn | The  state "fb-checkpresence.1.Thomas" will not longer exist in a future  version. Please use fb-checkpresence.1.Thomas.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:19.800 | warn | The  state "fb-checkpresence.1.Lars" will not longer exist in a future  version. Please use fb-checkpresence.1.Lars.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:19.577 | warn | The  state "fb-checkpresence.1.Nils" will not longer exist in a future  version. Please use fb-checkpresence.1.Nils.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:19.203 | info | createGlobalObjects finished successfully
fb-checkpresence.1 | 2023-02-08 19:11:18.542 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.1 | 2023-02-08 19:11:18.541 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.1 | 2023-02-08 19:11:18.540 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:18.540 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.1 | 2023-02-08 19:11:18.537 | warn | You should then manually delete the old states!
fb-checkpresence.1 | 2023-02-08 19:11:18.537 | warn | In  an future version some states are not more existent. Please use  compatibility = false to switch to the new handling of the states!


</body>
</html>

**Comment by afuerhoff** [comment]
Du kannst noch Kompatibilität in der Konfiguration abhaken. Dann gibt es noch weniger Meldungen. Die Objekte sind dann unter familymember zu finden. Vorher bitte den Adapter stoppen und mal alle Objekte der Instanz löschen. Dann die Einstellung ändern und neu starten.

**Comment by afuerhoff** [comment]
Bitte auch mal die Instanz auf Logstufe debug stellen und  dann vom Start die Meldungen posten.

**Comment by thomke67** [comment]
Gesagt, getan, 
Das Loging habe ich dann aber wieder abgestellt, weil nur noch die letzten Meldungen (ends after .... s) wiederholt wurden.....

<html><body>


fb-checkpresence.1 | 2023-02-08 20:03:51.783 | debug | loop main ends after 0,994143026 s
-- | -- | -- | --
fb-checkpresence.1 | 2023-02-08 20:03:48.788 | debug | loop family ends after 1,508045124 s
fb-checkpresence.1 | 2023-02-08 20:03:39.276 | debug | loop main ends after 1,9391441 s
fb-checkpresence.1 | 2023-02-08 20:03:36.264 | debug | loop family ends after 1,552866218 s
fb-checkpresence.1 | 2023-02-08 20:03:26.703 | debug | loop main ends after 1,80278194 s
fb-checkpresence.1 | 2023-02-08 20:03:23.621 | debug | loop family ends after 1,188723672 s
fb-checkpresence.1 | 2023-02-08 20:03:14.426 | debug | loop main ends after 0,816475785 s
fb-checkpresence.1 | 2023-02-08 20:03:11.606 | debug | loop family ends after 1,513986124 s
fb-checkpresence.1 | 2023-02-08 20:03:02.087 | debug | loop main ends after 0,507638471 s
fb-checkpresence.1 | 2023-02-08 20:02:59.577 | debug | loop family ends after 1,499320883 s
fb-checkpresence.1 | 2023-02-08 20:02:50.071 | debug | loop main ends after 0,999307795 s
fb-checkpresence.1 | 2023-02-08 20:02:47.071 | debug | loop family ends after 1,545530994 s
fb-checkpresence.1 | 2023-02-08 20:02:37.518 | debug | loop main ends after 0,998073795 s
fb-checkpresence.1 | 2023-02-08 20:02:34.517 | debug | loop family ends after 1,487692669 s
fb-checkpresence.1 | 2023-02-08 20:02:25.026 | debug | loop main ends after 1,10683492 s
fb-checkpresence.1 | 2023-02-08 20:02:22.012 | debug | loop family ends after 1,478169202 s
fb-checkpresence.1 | 2023-02-08 20:02:12.525 | debug | loop main ends after 1,9226402 s
fb-checkpresence.1 | 2023-02-08 20:02:09.513 | debug | loop family ends after 1,481701667 s
fb-checkpresence.1 | 2023-02-08 20:02:00.025 | debug | loop main ends after 1,17805327 s
fb-checkpresence.1 | 2023-02-08 20:01:57.006 | debug | loop family ends after 1,474154114 s
fb-checkpresence.1 | 2023-02-08 20:01:47.524 | debug | loop main ends after 1,7531334 s
fb-checkpresence.1 | 2023-02-08 20:01:44.515 | debug | loop family ends after 1,568695358 s
fb-checkpresence.1 | 2023-02-08 20:01:34.942 | debug | loop main ends after 1,3230437 s
fb-checkpresence.1 | 2023-02-08 20:01:31.938 | debug | loop family ends after 1,540797115 s
fb-checkpresence.1 | 2023-02-08 20:01:22.389 | debug | loop main ends after 0,999599861 s
fb-checkpresence.1 | 2023-02-08 20:01:19.387 | debug | loop family ends after 1,495307364 s
fb-checkpresence.1 | 2023-02-08 20:01:09.889 | debug | loop main ends after 0,992447507 s
fb-checkpresence.1 | 2023-02-08 20:01:06.894 | debug | loop family ends after 1,483208954 s
fb-checkpresence.1 | 2023-02-08 20:00:57.402 | debug | loop main ends after 1,12654365 s
fb-checkpresence.1 | 2023-02-08 20:00:54.389 | debug | loop family ends after 1,490470491 s
fb-checkpresence.1 | 2023-02-08 20:00:44.894 | debug | loop main ends after 1,224063291 s
fb-checkpresence.1 | 2023-02-08 20:00:41.667 | debug | loop family ends after 1,510982547 s
fb-checkpresence.1 | 2023-02-08 20:00:32.151 | debug | loop main ends after 1,17116814 s
fb-checkpresence.1 | 2023-02-08 20:00:29.131 | debug | loop family ends after 1,503250294 s
fb-checkpresence.1 | 2023-02-08 20:00:19.619 | debug | loop main ends after 1,3535390 s
fb-checkpresence.1 | 2023-02-08 20:00:16.612 | debug | loop family ends after 1,529688242 s
fb-checkpresence.1 | 2023-02-08 20:00:07.075 | debug | loop main ends after 0,817627594 s
fb-checkpresence.1 | 2023-02-08 20:00:04.255 | debug | loop family ends after 1,521947303 s
fb-checkpresence.1 | 2023-02-08 19:59:54.730 | debug | loop main ends after 1,9530206 s
fb-checkpresence.1 | 2023-02-08 19:59:51.719 | debug | loop family ends after 1,19063115 s
fb-checkpresence.1 | 2023-02-08 19:59:51.584 | warn | getActive  Nils:  Hosts:1 GetSpecificHostEntry: NoSuchEntryInArray -> please  check entry (mac, ip, hostname) in configuration! It is not listed in  the Fritzbox device list
fb-checkpresence.1 | 2023-02-08 19:59:49.699 | info | loop successfully started
fb-checkpresence.1 | 2023-02-08 19:59:49.698 | info | states successfully subscribed
fb-checkpresence.1 | 2023-02-08 19:59:49.696 | info | createMemberObjects finished successfully
fb-checkpresence.1 | 2023-02-08 19:59:49.696 | debug | enableHistory.2 Andrea true
fb-checkpresence.1 | 2023-02-08 19:59:49.386 | debug | enableHistory.2 Thomas true
fb-checkpresence.1 | 2023-02-08 19:59:49.123 | debug | enableHistory.2 Lars true
fb-checkpresence.1 | 2023-02-08 19:59:48.879 | debug | enableHistory.2 Nils true
fb-checkpresence.1 | 2023-02-08 19:59:48.342 | info | createGlobalObjects finished successfully
fb-checkpresence.1 | 2023-02-08 19:59:47.757 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.756 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.756 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.755 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.755 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.754 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.754 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.754 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.754 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.753 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-08 19:59:47.753 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.1 | 2023-02-08 19:59:47.752 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-08 19:59:47.752 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2023-02-08 19:59:47.751 | info | configuration default connection: 1.WANIPConnection.1
fb-checkpresence.1 | 2023-02-08 19:59:47.751 | debug | configuration filter delay: 10
fb-checkpresence.1 | 2023-02-08 19:59:47.751 | debug | configuration external ip address: true
fb-checkpresence.1 | 2023-02-08 19:59:47.750 | debug | configuration guest info: true
fb-checkpresence.1 | 2023-02-08 19:59:47.750 | debug | configuration qr code: false
fb-checkpresence.1 | 2023-02-08 19:59:47.750 | debug | configuration ssl: true
fb-checkpresence.1 | 2023-02-08 19:59:47.750 | debug | configuration compatibility: false
fb-checkpresence.1 | 2023-02-08 19:59:47.749 | debug | configuration whitelist: true
fb-checkpresence.1 | 2023-02-08 19:59:47.749 | debug | configuration mesh info: false
fb-checkpresence.1 | 2023-02-08 19:59:47.749 | debug | configuration fb-devices false
fb-checkpresence.1 | 2023-02-08 19:59:47.748 | debug | configuration  familymembers:  [{"enabled":true,"group":"","familymember":"Nils","devicename":"","macaddress":"F6:86:FE:6B:50:BA","ipaddress":"","usage":"MAC","usefilter":false,"comment":""},{"enabled":true,"group":"","familymember":"Lars","devicename":"","macaddress":"72:FD:DE:D6:02:EA","ipaddress":"","usage":"MAC","usefilter":false,"comment":""},{"enabled":true,"group":"","familymember":"Thomas","devicename":"","macaddress":"86:F8:BE:1E:4C:F8","ipaddress":"","usage":"MAC","usefilter":false,"comment":""},{"enabled":true,"group":"","familymember":"Andrea","devicename":"","macaddress":"A0:C9:A0:C2:06:5E","ipaddress":"","usage":"MAC","usefilter":false,"comment":""}]
fb-checkpresence.1 | 2023-02-08 19:59:47.747 | debug | configuration familymembers count: 4
fb-checkpresence.1 | 2023-02-08 19:59:47.747 | debug | configuration dateformat: <yyyy.mm.dd HH:MM:ss>
fb-checkpresence.1 | 2023-02-08 19:59:47.746 | debug | configuration history: <history.0>
fb-checkpresence.1 | 2023-02-08 19:59:47.746 | debug | configuration user: <Thomas>
fb-checkpresence.1 | 2023-02-08 19:59:47.745 | info | start  fb-checkpresence.1: FRITZ!Box 7330 SL (UI) version: not defined  ip-address: "192.168.178.2" - interval devices: 10 s - interval members:  10 s
fb-checkpresence.1 | 2023-02-08 19:59:47.597 | info | service X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-08 19:59:47.596 | info | service X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-08 19:59:47.580 | info | service WLANConfiguration3-GetSecurityKeys is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-08 19:59:47.580 | info | service WLANConfiguration3-GetInfo is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-08 19:59:47.579 | info | service WLANConfiguration3-SetEnable is not supported! Can not find service file! Feature is deactivated
fb-checkpresence.1 | 2023-02-08 19:59:46.590 | info | starting. Version 1.1.20 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v16.19.0, js-controller: 4.0.24
fb-checkpresence.1 | 2023-02-08 19:59:46.216 | debug | States connected to redis: 127.0.0.1:9000
fb-checkpresence.1 | 2023-02-08 19:59:46.172 | debug | States create User PubSub Client
fb-checkpresence.1 | 2023-02-08 19:59:46.170 | debug | States create System PubSub Client
fb-checkpresence.1 | 2023-02-08 19:59:46.144 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
fb-checkpresence.1 | 2023-02-08 19:59:46.097 | debug | Objects connected to redis: 127.0.0.1:9001
fb-checkpresence.1 | 2023-02-08 19:59:46.089 | debug | Objects client initialize lua scripts
fb-checkpresence.1 | 2023-02-08 19:59:45.904 | debug | Objects create User PubSub Client
fb-checkpresence.1 | 2023-02-08 19:59:45.902 | debug | Objects create System PubSub Client
fb-checkpresence.1 | 2023-02-08 19:59:45.896 | debug | Objects client ready ... initialize now
fb-checkpresence.1 | 2023-02-08 19:59:45.807 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
fb-checkpresence.1 | 2023-02-08 19:58:04.872 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.1 | 2023-02-08 19:58:04.871 | info | terminating
fb-checkpresence.1 | 2023-02-08 19:58:04.369 | info | cleaned everything up ...
fb-checkpresence.1 | 2023-02-08 19:58:04.365 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by afuerhoff** [comment]
Gerade nochmal in den Code gesehen. 
Diese Meldung "getActive Nils: Hosts:1 GetSpecificHostEntry: ......." bedeutet, dass die Mac-Adresse falsch sein könnte.

PS: Das Log müsste jetzt ja schon wesentlich besser aussehen -> mit Logstufe Info.

**Comment by thomke67** [comment]
MAC ist identisch und Nils wird erkannt!

**Comment by afuerhoff** [comment]
Wenn Nils erkannt wird, dann verstehe ich die Meldung nicht. Das dürfte eigentlich nicht sein. Bekommst Du denn im Log ein true und false zurückgeliefert, wenn Du das WLAN des Handys ein und ausschaltest?

Alles andere müsste jetzt ok sein. Oder?

**Comment by thomke67** [comment]
Was ist dass denn nun?

![grafik](https://user-images.githubusercontent.com/57798896/218512326-368924f9-727c-41d1-b824-58d9c00f4e7a.png)

**Comment by afuerhoff** [comment]
Hast Du etwas geändert? Kommen die Meldungen immer oder nur mal zwischendurch?

Wie gesagt, die Firmware ist alt und bei der Weiterentwicklung des Adapters kann darauf keine Rücksicht genommen werden. Auch der Router hat schon lange das Supportende bei AVM erreicht.

**Comment by thomke67** [comment]
Ich habe auf die neueste Version aktualisiert und da stand "Axios updated".......
Die Version hatte ich vorher eben noch nicht.

**Comment by afuerhoff** [comment]
Dann bitte wieder auf die Vorgänger Version gehen. Die Fritzbox ist einfach zu Alt.

**Comment by thomke67** [comment]
Die neue Version funktioniert auch. Ich habe einfach die Log Stufe erhöht. Jetzt kommen keine nervigen Warnungen mehr.....

**Comment by afuerhoff** [comment]
Sind die Meldungen denn nur sporadisch? Ansonsten dürfte keine Anwesenheit erkannt werden.

**Comment by thomke67** [comment]
Alle 13 Sekunden eine Warnung, aber nur von den Personen, die nicht an der speziellen Box angemeldet sind. Die anderen Personen werden nicht als Warnung im log angezeigt.
Die Personen, die an der Box angemeldet sind, werden auch dementsprechend in den Objekten angezeigt!

**Comment by afuerhoff** [comment]
Ok. Verstanden. 
Waren die Personen wo der Fehler kommt schon mal mit der zweiten Fritzbox connected?  
Sind die Personen bei der zweiten Box per Gast WLAN connected?

**Comment by thomke67** [comment]
1.  Frage: Ja
2.  Frage: Nein

**Comment by afuerhoff** [comment]
No error found.
