### ISSUE TITLE
fb-checkpresence kann nicht gestartet werden wegen Axios error

### ISSUE THREAD

**Issue by pantherossi** [afuerhoff/ioBroker.fb-checkpresence#188]
fb-checkpresence kann nach Installation auf einer recht frischen iobroker Installation mit aktuellem Softwarestand nicht gestartet werden. Details siehe Screenshot der Protokolle. iobroker läuft auf einer Proxmox Installation. Bisher gab es keine Auffälligkeiten. Auf einer iobroker Installation auf einem Raspi 4 gibt es keine Probleme mit dem selben Setup im Adapter

node.js  16.19.0
NPM 8.19.3
fb_checkpresence 1.1.25

Hat jemand eine Idee? 
![2023_02_19_13 23 39](https://user-images.githubusercontent.com/125803998/219949053-6b129f6e-0e7c-4951-a151-60ab680aa264.jpg)

**Comment by afuerhoff** [comment]
User und Passwort richtig angegeben?

**Comment by pantherossi** [comment]
Ja, aber die Felder zum Speichern blieben ausgegraut, User und passwort waren ohne effekt. Und starten ließ sich der Adapter nicht. Da in meiner alten raspi 4 Installation die Version 1.1.20 ohne Probleme läuft, habe ich in der proxmox Installation ebenfalls die alte 1.1.20 mit expertenmodus installiert, und siehe da alles prima.

**Comment by afuerhoff** [comment]
Wenn du jetzt nachdem es läuft das Update auf 1.1.25 machst, funktioniert es dann?

**Comment by pantherossi** [comment]
Hab gerade update auf 1.1.25 gemacht. An - und Abwesenheit simuliert, war ok. Und auch keine komischen Protokollmedlungen. Warum auch immer, jetzt ist alles fein.

**Comment by afuerhoff** [comment]
Mal ne Frage. Hattest du zu Anfang spezielle Sonderzeichen für IP, User oder Passwort benutzt? Weil ja der Speicher Button ausgegraut war. Das entsprechende fehlerhafte Feld wird nach dem verlassen Rot unterstrichen. Dann kann man nicht speichern und dann funktioniert natürlich auch der Adapter nicht.

**Comment by pantherossi** [comment]
Würde ich ausschließen. Mein pw enthält ein Fragezeichen, aber das ist ja unproblematisch. Ich habe es auch so oft installiert, deinstalliert, Iobroker neu gestartet, zugangsdaten erfasst, IP erfasst und alternativ nur den defaultwert. Es auch nie etwas rot geworden.

**Comment by afuerhoff** [comment]
Ich denke, ich weiß was das Problem war. Wenn eine Instanz neu angelegt wird, dann steht das Interval auf 1. Das bewirkt aber, dass der Speicher Button ausgegraut ist. Erst wenn man das Intervall auf mindestens 10 stellt, wird der Speicher Button bedienbar.
Das werde ich einer nächsten Version so ändern, dass die Grundeinstellung auf 60s steht.

**Comment by pantherossi** [comment]
Vielen Dank für die schnelle Analyse!
