### ISSUE TITLE
Feature request: Ändern der Zugangsprofile von Devices

### ISSUE THREAD

**Issue by Ilovegym66** [afuerhoff/ioBroker.fb-checkpresence#19]
Es wäre schön, wenn man die Zugangsprofile von Geräten per Adapter ändern könnte.
( Fritzbox -> Internet -> Filter -> Kindersicherung -> Internet sperren / Profil wechseln )

**Comment by afuerhoff** [comment]
Hallo, ich habe hierzu mal etwas recherchiert. Habe aber noch keine Möglichkeit gefunden.

**Comment by afuerhoff** [comment]
Thema werde ich aufgreifen nach dem Mesh fertig ist.

**Comment by Wildshunter** [comment]
Hört sich super an! BTW: Gibt das Protokoll auch einen Neustart der Fritzbox her? Habe hier zwei Instanzen Checkpresence mit zwei Fritzboxen im Gebrauch, die eine aktualisiert nach ca. einer Woche die Anwesenheiten nicht mehr, bzw. bleibt immer auf dem gleichen "Abwesenheitsstatus", nach Reboot der Fritzbox alles wieder okay.... Danke

**Comment by afuerhoff** [comment]
Hallo, die Testversion 1.1.0 kann von Github geladen werden.
Weitere Infos hier: https://forum.iobroker.net/topic/37959/test-adapter-fb-checkpresence-v1-1-x

Reboot ist noch nicht mit drin.

**Comment by maeb3** [comment]
Für das Ändern der Zugangsprofile von Devices in der Fritzbox gibt es hier ein Script von moelski, das bei mir gut funktioniert:
[https://forum.iobroker.net/topic/36095/internet-filter-in-der-fritzbox-mit-javascript-setzen](https://forum.iobroker.net/topic/36095/internet-filter-in-der-fritzbox-mit-javascript-setzen). Vielleicht kann man davon einige Teile "übernehmen", damit man das auch über den Adapter steuern kann.

**Comment by afuerhoff** [comment]
Hallo, das Script ist bekannt. In der neuen Version habe ich erstmal nur das reine aktivieren/deaktivieren eingebaut. Das war sehr einfach, da die neue Fritzbox Version 7.21 das jetzt unterstützt.
