### ISSUE TITLE
Neuer Datenpunkt CPU-Temperatur der Fritzbox

### ISSUE THREAD

**Issue by bambi-arch** [afuerhoff/ioBroker.fb-checkpresence#192]
Hallo, 
leider hab dich den Ideen-Button nicht gefunden! 
Besteht die Möglichkeit die CPU-Temperatur der Fritzbox als Datenpunkt anzeigen zu lassen?

Dankeschön!

**Comment by afuerhoff** [comment]
Hallo, ich kenne keine Möglichkeit die Temperatur per TR064 Schnittstelle auszulesen.
