### ISSUE TITLE
error: soap action status 500

### ISSUE THREAD

**Issue by Ilovegym66** [afuerhoff/ioBroker.fb-checkpresence#20]
with js-controller 3.1.4, node 12.6.3, linux mint 18.3, npm 6.14.5, fb-checkpresence v1.0.1, and fritzos 7.19-78939Beta this error appears:

`

fb-checkpresence.0 | 2020-05-14 07:43:24.797 | debug | (7833) checkPresence first run
-- | -- | -- | --
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | (7833) soapAction status 500
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | </s:Envelope>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | </s:Body>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | </s:Fault>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | </detail>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | </UPnPError>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <errorDescription>NoSuchEntryInArray</errorDescription>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <errorCode>714</errorCode>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <UPnPError xmlns="urn:dslforum-org:control-1-0">
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <detail>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <faultstring>UPnPError</faultstring>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <faultcode>s:Client</faultcode>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <s:Fault>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <s:Body>
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"  s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
fb-checkpresence.0 | 2020-05-14 07:43:24.797 | error | (7833) soapAction mesg<?xml version="1.0"?>
fb-checkpresence.0 | 2020-05-14 07:43:23.950 | debug | (7833) history Bernd true time: Thu May 14 2020 07:43:23 GMT+0200 (Central European Summer Time)
fb-checkpresence.0 | 2020-05-14 07:43:23.949 | debug | (7833) history Bernd true time: Thu May 14 2020 07:43:23 GMT+0200 (Central European Summer Time)

`

**Comment by afuerhoff** [comment]
Hallo, "NoSuchEntryInArray" deutet auf eine nicht vorhandene Mac in der Fritzbox hin. In den Familieneinstellungen muss es also eine falsche Mac-Adresse geben.

**Comment by Ilovegym66** [comment]
Hi, thank you, fixed with 1.0.2
