### ISSUE TITLE
Abfragen im MESH

### ISSUE THREAD

**Issue by docugraf** [afuerhoff/ioBroker.fb-checkpresence#206]
Wäre es möglich, die unterschiedlichen Fritzboxen im MESH zu unterscheiden? 
Ich habe mein LAN aufgeteilt in Wohnung und Garage , dazwischen 50m LANleitung, in der Garage der MESH-Repeater, wenn ich nun von der Strasse zur Garage gehe, soll nicht unbedingt die Wohnungstür aufgesperrt werden

**Comment by afuerhoff** [comment]
Hallo, wenn Du Mesh in den Einstellungen des Adapters aktiviert hast, wird bei den Devices angezeigt mit welchem Mesh Repeater das Gerät verbunden ist.

**Comment by GrayTheZebra** [comment]
Es wäre super wenn der "Link" auch in den jeweiligen Familienmitgliedern angezeigt werden würde und nicht nur unter fb-devices.

**Comment by afuerhoff** [comment]
Hallo, den State link werde ich in der nächsten Version direkt beim Familienmitglied mit anzeigen.
