### ISSUE TITLE
fb-checkpresence.<x>.presence not correct

### ISSUE THREAD

**Issue by LutzHelling** [afuerhoff/ioBroker.fb-checkpresence#21]
In my installation the indicator "fb-checkpresence.0.presence" ist set to "false" although "fb-checkpresence.0.presentMembers" is filled with two - all family - devices. Even "fb-checkpresence.0.presenceAll" ist set to "true", which actually is true. I guess that "fb-checkpresence.0.presence" should also be "true".

To reproduce: 
One Device has to be present - then watch flag "fb-checkpresence.0.presence" being shortly true, then changing to false.

![BugReport FB-Presence](https://user-images.githubusercontent.com/58373122/83336926-958d4600-a2b7-11ea-90f7-6511339c5a6b.png)

**Comment by afuerhoff** [comment]
I can't reproduce this behaviour. In my installation the values are correct. Have you an error message in the log? Can you please send me the log with loglevel debug from the adapter start on.

**Comment by LutzHelling** [comment]
right on the "presence"-flag is set correctly. I will stay muted until the situation described above will occur again and come bak to you with the logfile. thank you!
