### ISSUE TITLE
Statusupdate erst nach Restart der Instanz

### ISSUE THREAD

**Issue by Wildshunter** [afuerhoff/ioBroker.fb-checkpresence#22]
Version 1.03; Erstmal Danke für die Adapterentwicklung! Leider erfolgt der Statusupdate der Anwesenheit jeweils erst nach Restart der Instanz, obwohl Zeitintervall 1 Minute ausgewählt ist. Bitte um Info wenn LOGS benötigt werden und welche. Danke!

**Comment by afuerhoff** [comment]
Bitte Loglevel auf Debug stellen und dann posten.

**Comment by afuerhoff** [comment]
Hallo, hast du das Problem noch? Ich habe auf Github die Version 1.0.4 zum Testen hochgeladen.

**Comment by afuerhoff** [comment]
Hallo, da ich keine Rückmeldung bekommen habe schließe ich den Issue.
