### ISSUE TITLE
Datenpunkt presence auch für guest einfügen

### ISSUE THREAD

**Issue by m-s-b** [afuerhoff/ioBroker.fb-checkpresence#23]
Ich steuere einige Sachen über die Logik Gast anwesend ja/nein.
Natürlich kann ich mir einen eigenen Datenpunkt erzeugen, der bei guest; count >0 auf true geht. 
Fände es komfortabler wenn der Adapter auch unter guest einen presence true/false wie bei den Familienmitgliedern erzeugen würde.

**Comment by afuerhoff** [comment]
Hallo, hatte ich auch schon gesehen. Kommt im nächsten kleinen Update.

**Comment by m-s-b** [comment]
Super. Wo wir gerade dabei sind, wie wäre es pro Familienmitglied mit einem Datenpunkt  "actual_state" Anwesend/Abwesend, oder frei konfigurierbar? 
Hab für die Starsteite der VIS eine kleine Anwesenheitsliste.
![image](https://user-images.githubusercontent.com/46641961/84112363-e6740b80-aa28-11ea-8402-eab73238e7eb.png)
`Anwesend seit:{fb-checkpresence.0.Jessi.comming.lc;date(DD.MM hh:mm)}<br>
Abwesend seit:{fb-checkpresence.0.Jessi.going.lc;date(DD.MM hh:mm)}`
Mir würde eine Zeile mit dem aktuellen Status + TimeStamp reichen. Könnte man entweder mit einem "actual_state" lösen. Geht zwar auch über bindings, allerdings hab ich noch nicht verstanden ob und wie sehr deren Verwendung das System irgendwann bremst.

**Comment by afuerhoff** [comment]
Hallo, der Datenpunkt ist im Update 1.0.4 auf Github zum Testen drin.

**Comment by m-s-b** [comment]
Hi, 
hab die 1.0.4 getestet und funktioniert. 
Danke
Den "actual_state" setzte ich dann via binding um.
