### ISSUE TITLE
presence immer "true"

### ISSUE THREAD

**Issue by Hans-Zwiesel** [afuerhoff/ioBroker.fb-checkpresence#24]
FritzBox 7560, UniFi AP-nanoHD
2 SmartPhones im Gastnetz 192.168.179.xxx, deshalb Ident über MAC Adresse, eingetragen
als "Familienmitglied" und in der "Whitelist"

Wenn diese 2 SmartPhones abgemeldet sind und weder in der FritzBox noch im UniFi AP
als aktiv aufgeführt sind,
erscheinen aber auch nach 1 Std. immer noch in den Objekten:

fb-checkpresence.0.Galaxy-S7-edge.presence: true
fb-checkpresence.0.Samsung-Dani.presence: true

**Comment by afuerhoff** [comment]
Hallo, ich konnte den Fehler bei mir nicht nachstellen. Evtl. mal auf Log-Level Debug stellen und schauen, ob Fehler auftauchen. Dann das Log posten.

PS: Es gibt allerdings ein Problem bei Familienmitgliedern im Gastnetz. Die Fritzbox hat nur solange einen Eintrag zum Device, wie das Gerät aktiv ist. Danach kann die Mac-Adresse nicht mehr erkannt werden. Das liegt an der Fritzbox und kann nicht verhindert werden. Dazu müsste es auch Meldung im Log geben.

**Comment by Hans-Zwiesel** [comment]
Hallo,
zur Zeit kann ich leider die Anwesenheit der Smartphones nicht feststellen, werde ich aber nachholen.

Worin liegt eigentlich der Vorteil Deines Adapters gegenüber der tr-064??

**Comment by afuerhoff** [comment]
Hallo, es gibt keinen Vorteil. Mein Adapter hat einen anderen Fokus und hat sich dann nach und nach weiterentwickelt aufgrund des Inputs der User.

**Comment by Hans-Zwiesel** [comment]
Das Smartphone: Galaxy-S7-edge, 8C:F5:A3:7A:A1:AE ist nicht in der FritzBox und nicht im
UniFi AP sichtbar.
Trotzdem wird es mit fb-checkpresence.0.Galaxy-S7-edge.presence: true im ioBroker angezeigt.
Dabei wird jede Minute ein "warn" Eintrag im Logbuch erstellt:

fb-checkpresence.0 | 2020-06-19 06:40:13.774 | warn | (9769) macaddress 8C:F5:A3:7A:A1:AE from member Galaxy-S7-edge not found in fritzbox device list

**Comment by afuerhoff** [comment]
Die Abwesenheit kann bei Gästen scheinbar nicht korrekt ausgewertet werden, da die Funktion da keine Rückmeldung mehr von der Fritzbox bekommt. Ich werde einfach wenn der Fehler kommt die Anwesenheit auf Falle setzen. Anders kann man es bei Gästen nicht lösen. Werde ich beim nächsten Update berücksichtigen.

**Comment by afuerhoff** [comment]
Ich hab die Version 1.0.4 auf Github hochgeladen. Bitte testen, ob es jetzt funktioniert.

**Comment by afuerhoff** [comment]
Hallo, konntest du schon testen?

**Comment by afuerhoff** [comment]
Hallo, da ich keine Rückmeldung bekommen habe schließe ich den Issue.
