### ISSUE TITLE
Presence only using last device if a member has multiple devices

### ISSUE THREAD

**Issue by d4fseeker** [afuerhoff/ioBroker.fb-checkpresence#25]
**Describe the bug**  
When using the same member name on multiple devices, the "presence flag" and associated information is only taking into consideration the last device for that member.

**To Reproduce**  
1. Go to Adapter settings'
2. Add 2 entries for different devices for the same member
3. Attempt to offline/online either device. Only the last device in the list changes the status.

**Expected behavior**  
If at least one device is present, it should react from the first available device until the last available device for the same family member name. 

**Versions:**  
 - Adapter version: 10.3
 - JS-Controller version: 3.1.4
 - Node version: v10.21.0
 - Operating system: Debian 10.0 running on x86_64 (LXC Container)

**Additional context**  
The behaviour onfortunately complicates automation based on family member presence.

Thanks for your great work

**Comment by afuerhoff** [comment]
Hi, this isn't a bug. This feature isn't implemented yet. You can have no double member names in the list.

**Comment by afuerhoff** [comment]
Hi, I have uploaded the test version 1.1.3 on Github. Please test it and give feedback. Before, please save the configuration. The configuration has changed in the test version. The new feature is the group feature in the configuration. You can give in example 2 devices the same group. For this group you have additional states.

**Comment by afuerhoff** [comment]
Enhancement published with 1.1.4. Group feature could be used.
