### ISSUE TITLE
[bug]: HostnameTest in fb-devices.json ???

### ISSUE THREAD

**Issue by zImage-de** [afuerhoff/ioBroker.fb-checkpresence#257]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Seit dem letzten Update auf 1.2.3 ist der Keyord im fb-devices.json sting "HostnameTest" zuvor war es nur "Hostname"...
Vermute mal dass es ein BUG ist ... zuviel geTESTed ??

### To Reproduce

1. 1.2.3 istallieren 
2. auf Objekte fb-checkpresence.0.fb-devices.json string inhalt ansehen 

### Screenshots & Logfiles

[{"HostnameTest":"1Xxxxxxxxxxe","IP-Address":"192.168.299.299","MAC-Address":"GG:GG:GG:GG:GG:GG","Active":false,"Type":"-","Disabled":false},{"HostnameTest":"32c9","IP-Address":"192.168.299.256","MAC-Address":"GG:JJ:JJ:JJ:JJ:JJ","Active":true,"Type":"-","Disabled":false},

### Adapter version

1.2.3

### js-controller version

5.0.17

### Node version

v16.20.2

### Operating system

Linux

**Comment by afuerhoff** [comment]
Hab ich übersehen. Im nächsten Release ist das behoben.

**Comment by zImage-de** [comment]
Danke für deine Arbeit !!!

**Comment by afuerhoff** [comment]
Bitte v1.2.4 testen und kurze Rückmeldung geben ob ok. Wird noch etwas dauern bis die im latest Repository auftaucht.

**Comment by zImage-de** [comment]
DANKE, jetzt ist der JSON String OK :
[
  {
    "Hostname": "......
