### ISSUE TITLE
Fritz Box App geofancing als anwesenheitserkennung!?

### ISSUE THREAD

**Issue by Heisenberg2018** [afuerhoff/ioBroker.fb-checkpresence#258]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Die Anwesenheit per IP funktioniert nicht so zuverlässig, wenn man außer Haus geht dauert es einige Minuten bis man als abwesend erkannt wird.
Und wenn man nach Hause kommt dann nehmen die Kameras auch ein erst einmal auf bis das Handy wieder erkannt wird.

Dazu habe ich hier das Problem dass unsere Geräte sich zwischendurch spontan abmelden, obwohl überall stromsparfunktionen ausgeschaltet sind.

### Description

Wie auch immer, die Fritzbox App kann jetzt geofencing, damit könnte man doch sicherlich eine zuverlässigere Anwesenheit bewerkstelligen.
Außerdem könnten Kameras und Co schon deaktiviert werden kurz bevor man zu Hause ist.

### Additional context

Die geofencing Funktion ist jetzt flächendeckend ausgerollt und bekommt schon neue Funktionen, ist es möglich die standortdaten auszulesen?

https://stadt-bremerhaven.de/fritzapp-smarthome-geofencing-erlaubt-jetzt-automatisierte-ablaeufe/

![Screenshot_2024-02-19-16-34-20-977_com android chrome-edit](https://github.com/afuerhoff/ioBroker.fb-checkpresence/assets/32299008/51734114-24e6-429c-a0d4-7c484b050ac0)

**Comment by afuerhoff** [comment]
Hallo, das Geofencing wird über das Handy und die App geregelt. 
Man kann die Position nicht aus der Fritzbox auslesen. Die App müsste an ioBroker melden, ob sich das Handy im Geofencing Bereich befindet oder auch nicht. Die [ ioBroker vis App](https://www.iobroker.net/docu/index-37.htm?page_id=5026&lang=de#Batterie_und_Standort) soll das können.

**Comment by Heisenberg2018** [comment]
Ach dann ist hier ja der völlig falsche Bereich, alles klar dann mache ich hier zu.
