### ISSUE TITLE
[enhancement]: Datenpunkt für manuellen Update der Geräte 

### ISSUE THREAD

**Issue by zImage-de** [afuerhoff/ioBroker.fb-checkpresence#259]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Ich würde gerne manuell die Geräte (z.b. via javascript oder via VIS) aktualisieren können. 

### Description

Manuelle Aktialisierung der GFB-Geräte mittel Datenpunkt:
z.B fb-checkpresence.0.triggerupdate    (true/false)

**Comment by afuerhoff** [comment]
Was verstehst du unter GFB Geräte? Generell ist der Adapter für die Anwesenheits Erkennung gedacht. Updates gehören da eigentlich nicht dazu.

**Comment by zImage-de** [comment]
oh sorry da hab ich mich wohl nicht klar ausgedrückt ...
Also in der Einstellungen kann ich ja unter "Abfrageintervall in Sekunden" einstellen ... 
Manchmal hätte ich aber gerne eine Anbfrage manuell getriggert. 

Jetzt klar?

**Comment by afuerhoff** [comment]
Verstanden. Schau mal hier:
https://github.com/afuerhoff/ioBroker.fb-checkpresence?tab=readme-ov-file#manually-trigger-presence

**Comment by zImage-de** [comment]
Danke das ist das was ich suche... 
Leider funktioniert das nicht: Trotz Rückabe von true beleibt fb-checkpresence.0.info.lastUpdate unverändert ... 
Code
`    sendTo('fb-checkpresence.0', 'triggerPresence', {} , function (result) { console.log(result, 'info'); });   
`
Log:
`
9:42:12.758 | info | javascript.0 (422) script.js.common.Password: Update fb-devices
19:42:24.146 | info | javascript.0 (422) script.js.common.Password: true
`

**Comment by afuerhoff** [comment]
fb-checkpresence.0.info.lastUpdate ist sowas wie ein Alive Flag. Daran kann man sehen, ob noch Kontakt zur Fritzbox besteht.
Der Datenpunkt wird nicht beim manuellen Triggern gesetzt. 
Durch die Trigger-Funktion werden die Datenpunkte der Familienmitglieder neu aus der Fritzbox eingelesen. Das wars.
