### ISSUE TITLE
Mesh Status der Geräte als Objekt mit einfügen

### ISSUE THREAD

**Issue by lammy000** [afuerhoff/ioBroker.fb-checkpresence#27]
Es wäre super wenn bei den Geräten der jeweilige Mesh Access Point mit angezeigt wird über den sie gerade verbunden sind.
Damit könnte man das Geräte Orten wo es sich im Haus gerade ca. befindet.

**Comment by afuerhoff** [comment]
Ich habe die Meshdaten mal ausgelesen. Ich würde jedes Interface eines Device als Channel und dann die zugehörigen Daten einbinden.

**Comment by lammy000** [comment]
Hört sich doch gut an. Da wird dann auch Signalstärke und so ausgegeben oder?

**Comment by afuerhoff** [comment]
Werde ich mit vorsehen. Ich geb auch die Original Json Daten mit aus. Dann könnte man das auch in eigenen Scripten verarbeiten.

**Comment by afuerhoff** [comment]
Hallo, die Testversion 1.1.0 kann von Github geladen werden. 
Weitere Infos hier: https://forum.iobroker.net/topic/37959/test-adapter-fb-checkpresence-v1-1-x

**Comment by afuerhoff** [comment]
Its now implemented in stable version 1.1.0
