### ISSUE TITLE
Feature request: Gast Zugang ein/auschalten

### ISSUE THREAD

**Issue by PapaSpik3** [afuerhoff/ioBroker.fb-checkpresence#28]
Hallo wäre es möglich den Gastzugang ein bzw. aus zuschalten.

laut API scheint es zu funktionieren: http://www.apfel-z.net/artikel/Fritz_Box_API_TR_064_via_PHP/ vlt hilft das :)

Vielen Dank!

**Comment by afuerhoff** [comment]
Hatte ich auch schon dran gedacht. Im Moment bin ich an der Mesh Funktionalität. Danach würde ich mir das mit dem Gastzugang ansehen.

**Comment by afuerhoff** [comment]
Hallo, die Testversion 1.1.0 kann von Github geladen werden.
Weitere Infos hier: https://forum.iobroker.net/topic/37959/test-adapter-fb-checkpresence-v1-1-x

**Comment by afuerhoff** [comment]
Its now implemented in stable version 1.1.0
