### ISSUE TITLE
Feature request: absend & absentAll

### ISSUE THREAD

**Issue by duczz** [afuerhoff/ioBroker.fb-checkpresence#29]
Wäre es möglich 2 neue states anzulegen "absend und absentAll" wie bereits für prensent und presentAll?

**Comment by afuerhoff** [comment]
Hallo, die Testversion 1.1.0 kann von Github geladen werden.
Weitere Infos hier: https://forum.iobroker.net/topic/37959/test-adapter-fb-checkpresence-v1-1-x

**Comment by afuerhoff** [comment]
Its now implemented in the stable version 1.1.0
