### ISSUE TITLE
big detection delay

### ISSUE THREAD

**Issue by hschwane** [afuerhoff/ioBroker.fb-checkpresence#291]
Hi aluerhoff,
I like your adapter's features for presence detection, so I decided to switch and use it instead of the iobroker.tr-064 adapter i was using before. However I noticed that the detection delay of this adapter is much longer than the one of the tr-064. I ran both adapters simultaneously to compare (setting data polling interval to 10 seconds for both) and tested by connecting and disconnecting my phone from the wifi.  It took your adapter up to 40 seconds longer than the tr-064 adapter to detect a change in presence. 
Not sure if this is a bug or a feature, or if you want / can change anything about it.
For most people it might not even matter. I try to control lighting in my entrance area and the big delay makes it mostly useless.

**Comment by afuerhoff** [comment]
Could you provide all settings please.
If you have a filter setting then it could be that the time is longer. In my home network I have no delays.

**Comment by hschwane** [comment]
ah I think I found my mistake. 
I did not notice there was a second polling interval in the family tab until just now. 
So it was my own vault. If anything, you could consider writing down what the polling intervals are used for  in the title/description of the input fields.

Closing this and sorry for wasting your time.
