### ISSUE TITLE
[bug]: getExtIp: WANIPConnection:1 GetInfo: Internal Server Error -> Invalid Action AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by 2afs** [afuerhoff/ioBroker.fb-checkpresence#304]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

The following warning is regularly in the iobroker log:
<html>
<body>

getExtIp: WANIPConnection:1 GetInfo: Internal Server Error -> Invalid Action AxiosError: Request failed with status code 500
--

</body>
</html>

### To Reproduce

Connect the WAN interface to a Modem and connect to your Provider

### Adapter version

1.2.4

### js-controller version

6.0.11

### Node version

Node.js: v20.17.0

### Operating system

Linux iobroker 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Comment by afuerhoff** [comment]
I need more Information.

- Fritzbox type
- Firmware version FB
- Log Information from the start of the adapter with log level debug.

**Comment by 2afs** [comment]
Hi, thanks for the first feedback :)
Here are the information:
Fritzbox type: **7590**
Firmware version FB: **FRITZ!OS:[7.59] -[Version aktuell]**
Log Information from the start of the adapter with log level debug:
`<html>
<body>

fb-checkpresence.0 | 2024-09-06 13:05:04.289 | debug | getDeviceInfo activeCnt: 43
-- | -- | -- | --
fb-checkpresence.0 | 2024-09-06 13:05:01.996 | debug | loop main ends after 0,223853786 s
fb-checkpresence.0 | 2024-09-06 13:05:01.853 | warn | getExtIp: WANIPConnection:1 GetInfo: Internal Server Error -> Invalid Action AxiosError: Request failed with status code 500
fb-checkpresence.0 | 2024-09-06 13:04:59.770 | debug | loop family ends after 2,91892084 s
fb-checkpresence.0 | 2024-09-06 13:04:59.585 | debug | iPhone Dominik: No history item before this day is available
fb-checkpresence.0 | 2024-09-06 13:04:59.584 | debug | history iPhone Dominik cntHistory: 3
fb-checkpresence.0 | 2024-09-06 13:04:59.576 | debug | history cntActualDay: 4
fb-checkpresence.0 | 2024-09-06 13:04:59.386 | debug | S21-FE-von-Nathanael: No history item before this day is available
fb-checkpresence.0 | 2024-09-06 13:04:59.385 | debug | history S21-FE-von-Nathanael cntHistory: 3
fb-checkpresence.0 | 2024-09-06 13:04:59.379 | debug | history cntActualDay: 4
fb-checkpresence.0 | 2024-09-06 13:04:59.187 | debug | history susanneiphone12pro cntHistory: 8
fb-checkpresence.0 | 2024-09-06 13:04:59.180 | debug | history cntActualDay: 8
fb-checkpresence.0 | 2024-09-06 13:04:59.002 | debug | history iPhone-13-von-Alina cntHistory: 6
fb-checkpresence.0 | 2024-09-06 13:04:58.996 | debug | history cntActualDay: 6
fb-checkpresence.0 | 2024-09-06 13:04:58.823 | debug | S23-von-Fabienne: No history item before this day is available
fb-checkpresence.0 | 2024-09-06 13:04:58.822 | debug | history S23-von-Fabienne cntHistory: 3
fb-checkpresence.0 | 2024-09-06 13:04:58.816 | debug | history cntActualDay: 4
fb-checkpresence.0 | 2024-09-06 13:04:58.638 | debug | history S10-von-Andre cntHistory: 8
fb-checkpresence.0 | 2024-09-06 13:04:58.632 | debug | history cntActualDay: 8
fb-checkpresence.0 | 2024-09-06 13:04:58.603 | warn | getActiveiPhone Dominik: Warning: The configured mac-address for member iPhone Dominik was not found in the fritzbox. Please insert a valid mac-address!
fb-checkpresence.0 | 2024-09-06 13:04:58.602 | warn | getActiveS21-FE-von-Nathanael: Warning: The configured mac-address for member S21-FE-von-Nathanael was not found in the fritzbox. Please insert a valid mac-address!
fb-checkpresence.0 | 2024-09-06 13:04:56.677 | info | loop successfully started
fb-checkpresence.0 | 2024-09-06 13:04:56.675 | info | states successfully subscribed
fb-checkpresence.0 | 2024-09-06 13:04:56.671 | info | createFbDeviceObjects finished successfully
fb-checkpresence.0 | 2024-09-06 13:04:41.447 | warn | getAllFbObjects: To delete this device in the fritzbox please add the device manually in the fritzbox with a hostname and the shown mac-address. After a reboot you can hopefully delete the device.
fb-checkpresence.0 | 2024-09-06 13:04:41.446 | warn | getAllFbObjects: Hostname of fritzbox device 1A:8B:25:83:46:9F is empty!
fb-checkpresence.0 | 2024-09-06 13:04:40.640 | info | createMemberObjects finished successfully
fb-checkpresence.0 | 2024-09-06 13:04:39.218 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2024-09-06 13:04:38.684 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.683 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.683 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.682 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.682 | info | X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.682 | info | X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.682 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.682 | info | WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.681 | info | WLANConfiguration3-GetInfo is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.681 | info | WLANConfiguration3-SetEnable is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.681 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.681 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.681 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.680 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.680 | info | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.680 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.680 | info | Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.679 | info | Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0 | 2024-09-06 13:04:38.678 | info | configuration default connection: 1.WANIPConnection.1
fb-checkpresence.0 | 2024-09-06 13:04:38.678 | debug | configuration filter delay: 15
fb-checkpresence.0 | 2024-09-06 13:04:38.678 | debug | configuration external ip address: true
fb-checkpresence.0 | 2024-09-06 13:04:38.678 | debug | configuration guest info: true
fb-checkpresence.0 | 2024-09-06 13:04:38.678 | debug | configuration qr code: false
fb-checkpresence.0 | 2024-09-06 13:04:38.677 | debug | configuration ssl: true
fb-checkpresence.0 | 2024-09-06 13:04:38.677 | debug | configuration compatibility: false
fb-checkpresence.0 | 2024-09-06 13:04:38.676 | debug | configuration whitelist: false
fb-checkpresence.0 | 2024-09-06 13:04:38.676 | debug | configuration mesh info: true
fb-checkpresence.0 | 2024-09-06 13:04:38.676 | debug | configuration fb-devices true
fb-checkpresence.0 | 2024-09-06 13:04:38.675 | debug | configuration familymembers: [{"enabled":true,"group":"Familie1","familymember":"S10-von-Andre","devicename":"S10-von-Andre","macaddress":"8A:99:66:AD:57:40","ipaddress":"192.168.66.69","usage":"MAC","usefilter":false,"comment":"Andre S10"},{"enabled":true,"group":"Familie2","familymember":"S21-FE-von-Nathanael","devicename":"S21-FE-von-Nathanael","macaddress":"E2:36:D3:A1:85:2C","ipaddress":"192.168.179.2","usage":"MAC","usefilter":false,"comment":"Nathanael S21"},{"enabled":true,"group":"Familie1","familymember":"S23-von-Fabienne","devicename":"S23-von-Fabienne","macaddress":"9E:41:B9:E9:54:A5","ipaddress":"192.168.66.87","usage":"MAC","usefilter":false,"comment":"Fabi S23"},{"enabled":true,"group":"Familie1","familymember":"iPhone-13-von-Alina","devicename":"iPhone-13-von-Alina","macaddress":"62:6D:6D:EF:7F:C4","ipaddress":"192.168.66.57","usage":"MAC","usefilter":false,"comment":"Alina iPhone13"},{"enabled":true,"group":"Familie1","familymember":"susanneiphone12pro","devicename":"susanneiphone12pro","macaddress":"C2:55:80:7A:C1:AC","ipaddress":"192.168.66.78","usage":"MAC","usefilter":false,"comment":"Susi iPhone12"},{"enabled":true,"group":"Familie2","familymember":"iPhone Dominik","devicename":"iPhone-Dominik","macaddress":"52:8D:75:49:E9:D1","ipaddress":"192.168.79.6","usage":"MAC","usefilter":false,"comment":"Dominik iPhone"}]
fb-checkpresence.0 | 2024-09-06 13:04:38.675 | debug | configuration familymembers count: 6
fb-checkpresence.0 | 2024-09-06 13:04:38.674 | debug | configuration dateformat: <yyyy.mm.dd HH:MM:ss>
fb-checkpresence.0 | 2024-09-06 13:04:38.674 | debug | configuration history: <history.0>
fb-checkpresence.0 | 2024-09-06 13:04:38.673 | debug | configuration user: <iobroker>
fb-checkpresence.0 | 2024-09-06 13:04:38.671 | info | start fb-checkpresence.0: FRITZ!Box 7590 version: 154.07.59 ip-address: "192.168.66.250" - interval devices: 60 s - interval members: 60 s
fb-checkpresence.0 | 2024-09-06 13:04:34.799 | info | starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v20.17.0, js-controller: 6.0.11
fb-checkpresence.0 | 2024-09-06 13:04:33.057 | debug | States connected to redis: 127.0.0.1:6379
fb-checkpresence.0 | 2024-09-06 13:04:33.043 | debug | States create User PubSub Client
fb-checkpresence.0 | 2024-09-06 13:04:33.042 | debug | States create System PubSub Client
fb-checkpresence.0 | 2024-09-06 13:04:33.033 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
fb-checkpresence.0 | 2024-09-06 13:04:32.912 | debug | Objects connected to redis: 127.0.0.1:9001
fb-checkpresence.0 | 2024-09-06 13:04:32.902 | debug | Objects client initialize lua scripts
fb-checkpresence.0 | 2024-09-06 13:04:32.689 | debug | Objects create User PubSub Client
fb-checkpresence.0 | 2024-09-06 13:04:32.688 | debug | Objects create System PubSub Client
fb-checkpresence.0 | 2024-09-06 13:04:32.685 | debug | Objects client ready ... initialize now
fb-checkpresence.0 | 2024-09-06 13:04:32.589 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>`

**Comment by 2afs** [comment]
requested information attached

**Comment by afuerhoff** [comment]
Hi, could it be that theese configuration parameters are empty? The user is a must! Also the history adapter and the dateformat is used to calculate some values.
![image](https://github.com/user-attachments/assets/af09fa68-5f94-4017-9e66-bb095c4d34d1)
Here it seems is the MAC address in the family-member configuration wrong:
![image](https://github.com/user-attachments/assets/63ed2fb7-2552-402d-8af2-4ec553d4d53e)

PS: I have the same configuration as you and no problems with the external IP address.

**Comment by 2afs** [comment]
I think that was an issue with log Export and CSV: here you will find a screenshot. All information are available:
![image](https://github.com/user-attachments/assets/12fea546-4a40-4922-b935-73384c5e03a0)

**Comment by afuerhoff** [comment]
I seems that the server (Fritzbox) doesn't know the action to get the external IP. Please reboot the fritzbox. Hope that helps.
Again, I have no problems and therefore I can't reproduce the error. Is there any other thing special in your configuration?

**Comment by afuerhoff** [comment]
Issue closed. No error found.
