### ISSUE TITLE
devices active, devices inactive not updated after reconnect of line

### ISSUE THREAD

**Issue by Ilovegym66** [afuerhoff/ioBroker.fb-checkpresence#32]
FritzBox 7590, OS 7.21 release
fb-checkpresence Adapter Version 1.10 latest from Github
js-controller 3.16, linux debian 10 in lxc on proxmox.

Every night after the internet reconnect the adapter don't update the active devices, inactive devices any more.
A restart only of the adapter solves the problem.

I found it with logging my devices, after the reconnect the line is eval... thats not normal, because some devices are going off or on automatically..
In the picture you see the lines toggles around the measurements, but after the reconnect time in the night the line goes straight ahead. Than I restart the Adapter, thats the big break you see..

![grafik](https://user-images.githubusercontent.com/36229898/98097952-fd127780-1e8d-11eb-98f2-b863bbfeab0d.png)

**Comment by afuerhoff** [comment]
What is with the amount of active devices in the Fritzbox? Is the number of active device different to those in the adapter?

**Comment by Ilovegym66** [comment]
yes, thats than different, with my workaround it's fine now. ( I create a restart only of the adapter in the night after the internet re-connect of the box). Here from this night ( 24h logging, same as before )
![grafik](https://user-images.githubusercontent.com/36229898/98204458-5d5cf400-1f36-11eb-825a-4dd47eba5924.png)

**Comment by afuerhoff** [comment]
I can not reproduce this in my network. In the numbers in the fritzbox you have also devices, that are not relevant for the adapter. All telephones or Smart Home Devices. You must subtract this.

**Comment by Ilovegym66** [comment]
I know this. Okay, I start to debug more and set the adapter in the debug mode in the evening and make more investigations.
Can be, that other issues have impact to this.

**Comment by afuerhoff** [comment]
Hi, has you new informations about the issue?

**Comment by Ilovegym66** [comment]
Hi, sorry, I found nothing to clarify the issue, sometimes the number of devices are changing, sometimes not. After Re-Connection of the ISP in the night I let restart automatically the Adapter, and it looks, that this solves the problem.
But I don't know the reason, the adapter show no fault and there are no updates of the connected devices any more.. 
Same with FritzOS 7.21, and up with 7.24beta on two different 7590.
I can check the issue with a 7580 and 7560 in the next days, if I have time... so far..

**Comment by mikweb2017** [comment]
i have same problem whit Fritbox 6490 whit Fritos 7.20 i dont now was happen but dont update presence of mobile device.

**Comment by mikweb2017** [comment]
i rollback version 1.0.4  and work again

**Comment by Dragon0501** [comment]
same Problem here, same config as above

**Comment by afuerhoff** [comment]
@mikweb2017 @Dragon0501 
I need more input for further investigations.

**Comment by Dragon0501** [comment]
Which input? What can I do?

**Comment by mikweb2017** [comment]
@afuerhoff 
which information do you need?

**Comment by afuerhoff** [comment]
@Dragon0501 @mikweb2017 
Please switch the log level (instance page) to debug.
I need the log for the time point when the failure happens.

**Comment by Dragon0501** [comment]
How can I do that? activating loglevel debug...

**Comment by afuerhoff** [comment]
@Dragon0501 
On the instances page you have to switch on the expert Viel and the you can switch the log level from info to debug.

**Comment by kaip2503** [comment]
I have the same problem. I musst restart the adapter daily. 
I will try to give you the log, too.

**Comment by mikweb2017** [comment]
@afuerhoff 
as already written after rollback to 1.0.4 works again i should again change version and wait a few hours or days isn't there another possibility with older logs? i would like to avoid not receiving update at this time since i depend on other operations

**Comment by Dragon0501** [comment]
is 1.1.1 already useable or should we check it with 1.1.0?

**Comment by afuerhoff** [comment]
@Dragon0501 1.1.1 is in a test state. You can use it.

@mikweb2017 you can download an older log but  it must be on log level debug. I think that this is the problem.

**Comment by afuerhoff** [comment]
@mikweb2017, @Ilovegym66, @Dragon0501, @kaip2503  
Hi! Can you test the version 1.1.2 on Github.

**Comment by kaip2503** [comment]
Leider ohne erfolg. ich bekomme es auch nur noch zum laufen, wenn ich die Geräte neu einlese. Ein einfacher Neustart des adapters bringt nichts.

**Comment by afuerhoff** [comment]
@mikweb2017, @Ilovegym66, @Dragon0501, @kaip2503
I have updated the adapter on Github. Please install the bugfixed version for testing.

**Comment by mikweb2017** [comment]
work for me until now i give feedback tomorrow

**Comment by Ilovegym66** [comment]
works fine now.
