### ISSUE TITLE
FritzOS 7.24 and higher API changed with username and password

### ISSUE THREAD

**Issue by Ilovegym66** [afuerhoff/ioBroker.fb-checkpresence#35]
Hi,
not a bug report, but important for Beta-Testers and the future development,
in FritzOS 7.24 and higher are a change was done, take a look here, please:

https://avm.de/fritz-labor/frisch-aus-der-entwicklung/bekannte-probleme/

**Comment by afuerhoff** [comment]
Hi, thanks for information. I know this article.

**Comment by Ilovegym66** [comment]
fine, than can be closed :-)
