### ISSUE TITLE
Request: less logging on insufficient permissions

### ISSUE THREAD

**Issue by gswdn** [afuerhoff/ioBroker.fb-checkpresence#36]
Hi!

I don't feel comfortable providing the admin password of my Fritz!Box to ioBroker/fb-checkpresence. To me, this is a sensitive account with very high privileges. But that high privileges are not needed for just reading the devices and determining the presence status.

For that reason, I added a dedicated (service) account on my Fritz!Box with limited permissions:
![image](https://user-images.githubusercontent.com/52855342/104130733-a7b58380-5372-11eb-8fb9-9f2b1259baca.png)

Everything is working fine with these settings. It's ok for me, that I cannot make changes in ioBroker that require higher privileges on my Fritz!Box.

The only annoying thing is, that fb-checkpresence writes the "insufficient" permissions quite often to the log file:
![image](https://user-images.githubusercontent.com/52855342/104130607-f31b6200-5371-11eb-9cd4-b36b21fb04f0.png)

Could you please reduce the amount of logging in this case? Would it not be sufficient, if it's logged just one time on adapter startup or one time each day?

I really would appreciate a cleaner and smaller log file. And also a little less load on my system.

Thank you.

**Comment by afuerhoff** [comment]
I think I will restructure the handling with the fritzbox services. I can get the given access rights from the fritzbox user and then I can switch on or off an feature from the adapter. This avoid the logging.

**Comment by gswdn** [comment]
Nice! That even would be the cleanest solution since it also avoids fireing commands at the Fritz!Box that are not allowed.
Looking forward to seeing this in future release soon. Will really clean up my logs. Thank you!

**Comment by afuerhoff** [comment]
Hi! Can you test the version 1.1.2 on Github.

**Comment by gswdn** [comment]
Hi afuerhoff.

I've just installed and tested from GitHub. Great. Thank you so much for your good work and quick implementation.
Seems to work perfectly fine. The regular log warnings and errors disappeared. Just a few lines on - I guess - startup while checking permissions. Absolutely fine.
Also tested, if device and presence status are detected correctly. Seems to still work properly as well.

From my perspective: thumbs up. Good job.
Will monitor it closely within the next few days. If anything should pop up, I'll let you know.

Thank you again. Nice!

**Comment by afuerhoff** [comment]
I have just uploaded a new update on Github. It's the same version number. I have found a bug.

**Comment by gswdn** [comment]
Ok. I've just updated. Version number hasn't changed - as exected. Hope, the new version really got installed.
Still seems to work at the first glance. Will monitor it closely within the next few days.
Thank you again.

**Comment by afuerhoff** [comment]
Hi, I have uploaded the test version 1.1.3 on Github. Please test it and give feedback. Before, please save the configuration. The configuration has changed in the test version.

**Comment by afuerhoff** [comment]
1.1.4 with enhancement is published in stable repository.
