### ISSUE TITLE
Devices "leaving" and "coming back" periodically

### ISSUE THREAD

**Issue by EagleeyeKai** [afuerhoff/ioBroker.fb-checkpresence#37]
I have a mesh network here with AVW repeaters connected to the FB via LAN. My devices are logged periodically (about every hour) as "going", only to be logged again a few seconds later as "comming". The status itself is correct most of the time, but the timestamps are not usable. 

I would expect devices to be logged as "going" only when they actually leave the mesh WLAN. In my case, however, the error described above also occurs with devices that are not moved and always have the best WLAN reception.

**Versions:**  
 - Adapter version: 1.10
 - JS-Controller version: 3.1.6
 - Node version: 12.18.4
 - Operating system: Raspbian (Pi 4)

**Comment by afuerhoff** [comment]
Which Fritzbox firmware version do you have? With the new 7.2x the behaviour changes. Formerly the Fritzbox changed after 10 minutes to inactive. Now after some seconds they changed to inactive. A short disconnect then you can see as going and after some seconds as comming. In a new adapter version I will implement a delay.

**Comment by EagleeyeKai** [comment]
I am on the latest available version for my Fritzbox 6490 which is 7.20

A short delay seems to be good idea. Thanks for replying this quick!

**Comment by afuerhoff** [comment]
Hi, I have uploaded the test version 1.1.3 on Github. Please test it and give feedback. Before, please save the configuration. The configuration has changed in the test version.

**Comment by afuerhoff** [comment]
Enhancement is published with 1.1.4
