### ISSUE TITLE
can't start the adapter Error: Can not read hostlist path

### ISSUE THREAD

**Issue by mcbirne** [afuerhoff/ioBroker.fb-checkpresence#38]
since today I have a problem with the adapter.
fb-checkpresence.0 | 2021-02-17 08:17:21.100 | error | (4980) createFbDeviceObjects -> can't read devices from fritzbox! Adapter stops
-- | -- | -- | --
fb-checkpresence.0 | 2021-02-17 08:17:21.100 | error | (4980) getDeviceList: "Can not read hostlist path"
fb-checkpresence.0 | 2021-02-17 08:17:21.099 | error | (4980) soapAction /upnp/control/hosts X_AVM-DE_GetHostListPath status=ETIMEDOUT errNo=5 connect ETIMEDOUT 192.168.178.1:49443

I try to reinstall die adapter but it doesn't work.

**Comment by afuerhoff** [comment]
Hi, reboot of fritzbox can help.

**Comment by mcbirne** [comment]
After the reboot it works. Thanks

**Comment by afuerhoff** [comment]
Problem solved
