### ISSUE TITLE
Adapter dont start Again

### ISSUE THREAD

**Issue by mikweb2017** [afuerhoff/ioBroker.fb-checkpresence#39]
fb-checkpresence.0 | 2021-02-23 23:34:30.443 | info | (32454) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
fb-checkpresence.0 | 2021-02-23 23:34:30.442 | info | (32454) terminating
fb-checkpresence.0 | 2021-02-23 23:34:30.441 | info | (32454) cleaned everything up ...
fb-checkpresence.0 | 2021-02-23 23:34:30.440 | info | (32454) Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.0 | 2021-02-23 23:34:30.396 | error | (32454) createFbDeviceObjects -> can't read devices from fritzbox! Adapter stops
fb-checkpresence.0 | 2021-02-23 23:34:30.396 | error | (32454) getDeviceList: "Can not read hostlist path"
fb-checkpresence.0 | 2021-02-23 23:34:30.395 | error | (32454) soapAction X_AVM-DE_GetHostListPath status=null errNo=0
fb-checkpresence.0 | 2021-02-23 23:34:29.779 | info | (32454) createMemberObjects finished successfully
fb-checkpresence.0 | 2021-02-23 23:34:29.408 | info | (32454) createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-02-23 23:34:29.196 | info | (32454) service DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2021-02-23 23:34:29.181 | info | (32454) service X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2021-02-23 23:34:29.164 | info | (32454) service X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2021-02-23 23:34:29.147 | info | (32454) service DeviceInfo1-GetInfo is supported

FB  reboot  dont Work again
Iobroker Reboot dont Work again
Raspi Reboot dont Work again
fritzbox 6490 Fritz os  7.20

(32726) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.20.2, js-controller: 3.1.6
--

**Comment by afuerhoff** [comment]
Please switch the instance to log level debug and post the log again. I think it is not a problem of the adapter.

**Comment by mikweb2017** [comment]
resence.0	2021-02-24 07:44:43.007	error	(31227) getGuestWlan: "Can not read status of guest wlan null"
fb-checkpresence.0	2021-02-24 07:44:43.006	error	(31227) soapAction /upnp/control/wlanconfig3 GetInfo status=ECONNABORTED errNo=5 timeout of 10000ms exceeded
fb-checkpresence.0	2021-02-24 07:44:32.996	error	(31227) getExtIp: "Can not read external ip address null"
fb-checkpresence.0	2021-02-24 07:44:12.982	warn	(31227) connectionCheck: "can not connect to fritzbox!"
fb-checkpresence.0	2021-02-24 07:44:12.980	error	(31227) soapAction /upnp/control/hosts GetHostNumberOfEntries status=ECONNABORTED errNo=5 timeout of 10000ms exceeded
fb-checkpresence.0	2021-02-24 07:43:57.903	info	(31227) createMemberObjects finished successfully
fb-checkpresence.0	2021-02-24 07:43:57.563	info	(31227) createGlobalObjects finished successfully
fb-checkpresence.0	2021-02-24 07:43:56.980	info	(31227) service LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0	2021-02-24 07:43:56.859	info	(31227) service DeviceConfig1-Reboot is supported
fb-checkpresence.0	2021-02-24 07:43:56.842	info	(31227) service X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0	2021-02-24 07:43:56.823	info	(31227) service X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0	2021-02-24 07:43:56.805	info	(31227) service DeviceInfo1-GetInfo is supported
fb-checkpresence.0	2021-02-24 07:43:56.786	info	(31227) service WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0	2021-02-24 07:43:56.760	info	(31227) service WLANConfiguration3-GetInfo is supported
fb-checkpresence.0	2021-02-24 07:43:56.738	info	(31227) service WLANConfiguration3-SetEnable is supported
fb-checkpresence.0	2021-02-24 07:43:56.708	info	(31227) service WANPPPConnection1-GetInfo is supported
fb-checkpresence.0	2021-02-24 07:43:56.686	info	(31227) service DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0	2021-02-24 07:43:56.650	info	(31227) service Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0	2021-02-24 07:43:56.629	info	(31227) service Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0	2021-02-24 07:43:56.611	info	(31227) service Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0	2021-02-24 07:43:56.594	info	(31227) service Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0	2021-02-24 07:43:56.347	info	(31227) start fb-checkpresence: ip-address: "fritz.box" - interval devices: 1 Min. - interval members: 30 s
fb-checkpresence.0	2021-02-24 07:43:56.317	info	(31227) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.20.2, js-controller: 3.1.6

**Comment by mikweb2017** [comment]
![Bildschirmfoto 2021-02-24 um 07 50 19](https://user-images.githubusercontent.com/30271757/108959710-1295f200-7675-11eb-8a8e-348d7decb1e6.png)
jetzt nach anhaken geht wieder
