### ISSUE TITLE
Diskrepanz zwischen Familienmitglied und FB devices....

### ISSUE THREAD

**Issue by Dragon0501** [afuerhoff/ioBroker.fb-checkpresence#42]
Es ist die selbe Konfiguration wie bei Neustart Problem, lediglich die Firmware der FB 7590 wurde auf 7.25 geupdated. Geräte bei Familien mitglieder werden die Stati nicht aktualisiert. Bei den FB devices schon...

**Comment by Dragon0501** [comment]
Heist also ein und das selbe Gerät steht unter FB devices als False, was richtig ist und bei Familienmitglieder als True, was falsch ist. Wie ist denn soetwas möglich?

**Comment by afuerhoff** [comment]
Wie ist die Einstellung der Familienmitglieder? Verwendest Du die IP oder Mac? 
Bei den Devices wird ja einfach alles eingelesen, ohne speziell nach irgend etwas zu selektieren. 
Bei den Familienmitgliedern schaue ich nach der MAC oder IP und lese dann die Daten explizit aus. 
Die IP muss aber in der Fritzbox fest vorgegeben werden, wenn man sie verwendet. 
Sonst geht es nur nach MAC. Die MAC darf im Handy nicht verschleiert werden. Sonst funktioniert es auch nicht. 
Stimmt die MAC und die IP mit denen in Devices überein?

**Comment by Dragon0501** [comment]
Es hat bisher immer alles einwandfrei funktioniert und nun muss ich dir leiser ein Geständnis machen... Der FritzRepeater hatte sich aufgehängt. Da lag das Problem. rebootet und läuft wieder... Entschuldige...

**Comment by afuerhoff** [comment]
Kein Problem. Dann kann das Ticket ja geschlossen werden.

**Comment by Dragon0501** [comment]
Vielen Dank trotzdem für die schnelle Unterstützung!
