### ISSUE TITLE
usage of deprecated node package crypto@1.0.1

### ISSUE THREAD

**Issue by chris299** [afuerhoff/ioBroker.fb-checkpresence#5]
**Describe the bug**  
usage of deprecated node package crypto@1.0.1

**To Reproduce**  
install from GitHub URL in IOBroker

**Expected behavior**  
no error message during install

**Screenshots & Logfiles**  
Install output:
`$ ./iobroker url "https://github.com/afuerhoff/ioBroker.fb-checkpresence" --debug
install https://github.com/afuerhoff/ioBroker.fb-checkpresence/tarball/master
npm install https://github.com/afuerhoff/ioBroker.fb-checkpresence/tarball/master --production --save --prefix "/usr/local/iobroker" (System call)
npm
 WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
+ iobroker.fb-checkpresence@0.0.7added 6 packages from 7 contributors and audited 4673 packages in 6.229s

found 60 vulnerabilities (43 low, 17 high)  run `npm audit fix` to fix them, or `npm audit` for details

process exited with code 0`

**Versions:**  
 - Adapter version: 0.0.7
 - JS-Controller version: 1.5.3
 - Node version: 10.17
 - Operating system: OSX

**Additional context**  
-

**Comment by afuerhoff** [comment]
solved in version 0.2.0
