### ISSUE TITLE
adapter termination after upgrade 1.1.4

### ISSUE THREAD

**Issue by softwarecrash** [afuerhoff/ioBroker.fb-checkpresence#51]
**Describe the bug**  

**To Reproduce**  
after update from 1.1.0 to 1.1.4 (stable)
fritzbox 6820
testet with and without ssl
fritzbox reboot not help

**Expected behavior**  

**Screenshots & Logfiles**  

fb-checkpresence.0 | 2021-06-02 19:45:33.431 | info | (8948) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
fb-checkpresence.0 | 2021-06-02 19:45:33.430 | info | (8948) terminating
fb-checkpresence.0 | 2021-06-02 19:45:32.928 | info | (8948) cleaned everything up ...
fb-checkpresence.0 | 2021-06-02 19:45:32.927 | info | (8948) Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.0 | 2021-06-02 19:45:32.851 | warn | (8948) onReady:  Fb init: checkServices: checkService Error service  WLANConfiguration3-SetEnable is not supported! Can not find service  file! Feature is deactivated
fb-checkpresence.0 | 2021-06-02 19:45:32.325 | info | (8948) starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v10.24.1, js-controller: 3.2.16
fb-checkpresence.0 | 2021-06-02 19:45:32.116 | debug | (8948) statesDB connected
fb-checkpresence.0 | 2021-06-02 19:45:32.115 | debug | (8948) States connected to redis: 127.0.0.1:9000
fb-checkpresence.0 | 2021-06-02 19:45:32.109 | debug | (8948) States create User PubSub Client
fb-checkpresence.0 | 2021-06-02 19:45:32.108 | debug | (8948) States create System PubSub Client
fb-checkpresence.0 | 2021-06-02 19:45:32.101 | debug | (8948) Redis States: Use Redis connection: 127.0.0.1:9000
fb-checkpresence.0 | 2021-06-02 19:45:32.098 | debug | (8948) objectDB connected
fb-checkpresence.0 | 2021-06-02 19:45:32.087 | debug | (8948) Objects connected to redis: 127.0.0.1:9001
fb-checkpresence.0 | 2021-06-02 19:45:32.072 | debug | (8948) Objects client initialize lua scripts
fb-checkpresence.0 | 2021-06-02 19:45:32.072 | debug | (8948) Objects create User PubSub Client
fb-checkpresence.0 | 2021-06-02 19:45:32.071 | debug | (8948) Objects create System PubSub Client
fb-checkpresence.0 | 2021-06-02 19:45:32.067 | debug | (8948) Objects client ready ... initialize now
fb-checkpresence.0 | 2021-06-02 19:45:32.021 | debug | (8948) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by afuerhoff** [comment]
Please check if the github version solves the problem. 
Please install with url https://github.com/afuerhoff/ioBroker.fb-checkpresence

**Comment by softwarecrash** [comment]
> https://github.com/afuerhoff/ioBroker.fb-checkpresence

ah thanks, that work

**Comment by afuerhoff** [comment]
Info: The new version 1.1.5 will be shortly updated in the latest repository.
