### ISSUE TITLE
presence State always false after latest Update

### ISSUE THREAD

**Issue by phg2k** [afuerhoff/ioBroker.fb-checkpresence#52]
Hello!
Even with presenceAll = true the object presence is set to false since last update to 1.1.4

Danke für einen schnellen Fix!
PhG

**Comment by afuerhoff** [comment]
Wie wurde denn die Familienmitglieder konfiguriert? 
Kompatibilität?
Gruppe?

**Comment by phg2k** [comment]
Hi! Kompatibilität war aktiviert. Hab es nun deaktiviert - fb-checkpresence.0.presence steht immer noch auf false...
Keine Gruppe.
Was genau meinst du mit "konfiguriert"?

**Comment by afuerhoff** [comment]
Wenn Kompatibilität deaktiviert ist, werden alle States der Familienmitglieder im Ordner familyMembers angelegt. Ist eine Gruppe vergeben, dann werden unterhalb der Gruppe die States angelegt. Die alten States werden nicht gelöscht, aber auch nicht mehr aktualisiert. 
Mit Kompatibilität gleich true und ohne Gruppenname ist alles beim Alten. Dieser Modus wird aber nicht mehr lange supportet. Da kommen auch entsprechende Mitteilungen im Log.

**Comment by afuerhoff** [comment]
Falschen Button gedrückt. Sorry

**Comment by phg2k** [comment]
Ja, vielen Dank dir!
Foglendes habe ich gemacht:
- Kompabilität rausgenommen
- Gruppe eingetragen ("P6")
--> unter familyMembers ist die Gruppe ersichtlich.
Was mich wundert: wieder
fb-checkpresence.0.familyMembers.P6.presence = false
fb-checkpresence.0.familyMembers.P6.presenceAll = true
Selbes ein Level höher (ohne ".P6")

Für mich kann das schon rein logisch nicht sein?
Kannst du mir nochmal nen Tipp geben - Denkfehler?

**Comment by afuerhoff** [comment]
Kannst du mal ein Log im Loglevel debug posten. Vom Start an. Das Verhalten ist eigenartig. Was passiert wenn es einen Wechsel in der Anwesenheit gab?

**Comment by phg2k** [comment]
Sorry, war unterwegs...
Ich lösche gerade mal die komplette Instanz und alle zugehörigen Objekt.
Dann neu...

**Comment by phg2k** [comment]
Hier noch das Log:
`



fb-checkpresence.0 | 2021-06-07 22:31:12.717 | warn | (24068) getActive iPhonevon*****: Warning: The configured mac-address for member iPhonevon***** was not found. Please insert a valid mac-address!
-- | -- | -- | --
fb-checkpresence.0 | 2021-06-07 22:31:11.482 | info | (24068) loop successfully started
fb-checkpresence.0 | 2021-06-07 22:31:11.480 | info | (24068) states successfully subscribed
fb-checkpresence.0 | 2021-06-07 22:31:11.476 | info | (24068) createFbDeviceObjects finished successfully
fb-checkpresence.0 | 2021-06-07 22:31:07.043 | info | (24068) createMemberObjects finished successfully
fb-checkpresence.0 | 2021-06-07 22:31:07.042 | info | (24068) History function for phgS20ultra2 disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-06-07 22:31:06.961 | info | (24068) History function for phgS20ultra disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-06-07 22:31:06.876 | info | (24068) History function for iPhonevon*****2 disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-06-07 22:31:06.753 | info | (24068) History function for iPhonevon***** disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-06-07 22:31:06.475 | info | (24068) createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-06-07 22:31:06.007 | warn | (24068) The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-06-07 22:31:06.006 | warn | (24068) The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-06-07 22:31:06.006 | warn | (24068) The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-06-07 22:31:06.006 | warn | (24068) The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-06-07 22:31:06.003 | warn | (24068) You should then manually delete the old states!
fb-checkpresence.0 | 2021-06-07 22:31:06.003 | warn | (24068) In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2021-06-07 22:31:05.974 | info | (24068) Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.973 | info | (24068) LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.973 | info | (24068) WANPPPConnection1-ForceTermination is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.973 | info | (24068) DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.972 | info | (24068) X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.972 | info | (24068) X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.972 | info | (24068) DeviceInfo1-GetInfo is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.971 | info | (24068) WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.971 | info | (24068) WLANConfiguration3-GetInfo is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.971 | info | (24068) WLANConfiguration3-SetEnable is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.970 | info | (24068) WANIPConnection1-GetInfo is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.970 | info | (24068) WANPPPConnection1-GetInfo is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.969 | info | (24068) WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.969 | info | (24068) DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.969 | info | (24068) Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.968 | info | (24068) Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.968 | info | (24068) Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.967 | info | (24068) Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0 | 2021-06-07 22:31:05.967 | info | (24068) configuration default connection: 1.WANIPConnection.1
fb-checkpresence.0 | 2021-06-07 22:31:05.963 | info | (24068) start fb-checkpresence.0: FRITZ!Box 6591 Cable version: 161.07.22 ip-address: "192.168.1.1" - interval devices: 1 min. - interval members: 60 s
fb-checkpresence.0 | 2021-06-07 22:31:05.269 | info | (24068) starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.22.1, js-controller: 3.2.16
fb-checkpresence.0 | 2021-06-07 22:31:01.115 | info | (23864) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2021-06-07 22:31:01.114 | info | (23864) terminating
fb-checkpresence.0 | 2021-06-07 22:31:00.612 | info | (23864) cleaned everything up ...
fb-checkpresence.0 | 2021-06-07 22:31:00.604 | info | (23864) Got terminate signal TERMINATE_YOURSELF



`

**Comment by afuerhoff** [comment]
Das Log bräuchte ich mit Logstufe debug.
Kannst du mal einen History Adapter für die volle Funktionalität auswählen.

**Comment by mikweb2017** [comment]
+++++++++++++++++++++++++++
fb-checkpresence.0 | 2021-06-08 08:30:33.914 | warn | (16650) getActive iPhone : Warning: The configured mac-address for member iPhone von Daniele was not found. Please insert a valid mac-address!
-- | -- | -- | --
+++++++++++++++++++++++++++

So wie es aussieht hab ich dasselbe Problem. Bin schon auf Version 1.15 aber Änderungen von iphone werden nicht mehr erkannt. android Geräte kein Problem

**Comment by phg2k** [comment]
Hi!
Mach ich gern! Wo stelle ich das Loglevel?

VG

afuerhoff ***@***.***> schrieb am Di., 8. Juni 2021, 07:37:

**Comment by afuerhoff** [comment]
@phg2k 
Loglevel kannst du unter Instanzen einstellen.

**Comment by afuerhoff** [comment]
@mikweb2017, @phg2k 
Ist bei den Iphones eine feste Mac Adresse eingestellt. Ansonsten wird die ständig geändert. Oder einfach anstatt z.B. Mac den in der Fritzbox vergebenen Hostname in der Konfiguration verwenden.

**Comment by mikweb2017** [comment]
![Bildschirmfoto 2021-06-08 um 11 21 01](https://user-images.githubusercontent.com/30271757/121160419-5be90680-c84c-11eb-8d16-6e5adb02666c.png)
![Bildschirmfoto 2021-06-08 um 11 24 06](https://user-images.githubusercontent.com/30271757/121160435-5f7c8d80-c84c-11eb-8a64-21fd07c833ca.png)
ich habe ein festes IP vergeben.

**Comment by afuerhoff** [comment]
@mikweb2017 
Ich meinte etwas anderes. Eine Einstellung im iPhone.
Siehe hier:
https://www.mactechnews.de/news/article/iOS-14-Verschleierung-der-MAC-Adresse-sorgt-fuer-besseren-Schutz-der-Privatsphaere-175363.html

**Comment by afuerhoff** [comment]
@phg2k 
Da ist eine Meldung im Log, dass die Mac Adresse nicht in der Fritzbox gefunden wird. Bitte überprüfen. Du kannst die Daten mit dem Button "Familienmitglieder hinzufügen" aktualisieren.

**Comment by mikweb2017** [comment]
leider  auch nicht geholfen Status wird nicht geupdatet für Das IPhone.

**Comment by phg2k** [comment]
@afuerhoff : ein Update: auch wenn ich auf "IP" umstelle erhalte ich die Warnung
" getActive phgS20ultra2: Warning: The configured mac-address for member phgS20ultra2 was not found. Please insert a valid mac-address!"
Diese jeweils nur für ein Handy. Wenn ich das betroffene entferne, dann für das nächste in der Liste...
Adapter neu als Instanz hinzugefügt, die Geräte neu von der FB gelesen....

**Comment by mikweb2017** [comment]
![Bildschirmfoto 2021-06-08 um 13 08 08](https://user-images.githubusercontent.com/30271757/121174807-9eb1db00-c85a-11eb-986c-6fd7e03e33a1.png)
unter Familymember wird IPhone nicht aktualisiert
unter FB-device schon  bzw  wechselt zum aktiv.

**Comment by mikweb2017** [comment]
also  für mich erstmal gelöst ich prüfen jetzt unter fb-devices villeicht ist erstmal ein lösung auch für dich @phg2k

**Comment by phg2k** [comment]
@mikweb2017 danke dir für den Workaround. Tatsächlich bei mir das selbe.
Was mir noch auffiel: 
*.presenceAll = true und gelichzeitgi (!) *absenceAll = true

**Comment by afuerhoff** [comment]
Seid ihr ganz sicher, das die in der Konfiguration eingestellt Mac oder IP auch unter fb-devices identisch ist?
Um das Problem, wenn es denn eines ist, einzukreisen, brauche ich mal die Daten eines Devices aus fb-devices und die entsprechenden Konfigurationsdaten aus den Familieneinstellungen. 
Die Quelle, ob ein Device aktiv ist, ist die gleiche. Ganz egal ob unter Devices oder Familienmitglieder. 
Habt ihr mal die Einstellung mit Hostname benutzt (Mac oder IP auf Hostname umschalten)?

**Comment by mikweb2017** [comment]
![Bildschirmfoto 2021-06-09 um 08 46 35](https://user-images.githubusercontent.com/30271757/121306768-8778f900-c8ff-11eb-9760-3a54c522091c.png)
ja ich bin sicher  ich hatte vorher schon alles probiert IP Hostname  MAC Objekte gelöscht  um so weiter.

**Comment by mikweb2017** [comment]
hat evtl mit den Admin adapter zu tun? bin noch auf die version 4 .

**Comment by afuerhoff** [comment]
@mikweb2017 
Was man erkennen kann in den Bildern ist, dass das Device mehrfach in der Fritzbox gelistet ist. Ganz klar ein Zeichen für die Mac Verschleierung im Handy. Hast du wirklich die aktive Mac in der Fritzbox ausgewählt?

**Comment by mikweb2017** [comment]
ja und Nein war so bis gestern  dann habe ich deine link verfolgt und die Einstellung auf mein iPhone  deaktiviert.

**Comment by afuerhoff** [comment]
Wichtig ist, dass jetzt auch die richtige Mac ausgewählt ist. Für das Problem mit der Verschleierung habe ich die Auswertung über Hostname eingeführt. Der muss allerdings identisch zu dem in der Fritzbox sein. In der Fritzbox muss man darauf achten, dass auch nur dieses Device dann den Namen hat.

**Comment by phg2k** [comment]
Nochmal zum Verständnis und zum weiteren Test:
Ich würde nun 
- alle Datenpunkte / Objekte löschen
- die Instanz löschen
- neue Instanz installieren
- Loglevel auf debug
- alles Geräte von FB laden
- In die Familie nur 1 Gerät (Samsung) aufnehmen
- Erkennung über IP
- Kompatibilität aus
---> Testen
-> OK?

**Comment by afuerhoff** [comment]
1. In der Konfiguration den Button Familienmitglieder hinzufügen drücken und kontrollieren (FRITZBOX), das das richtige aktive Device ausgewählt ist. Nicht eine deaktive Kopie mit anderer Mac Adresse (Es gibt mit gleichem Hostname unterschiedliche Einträge in der Fritzbox). Die sicherste Methode ist, wenn man Hostname in der Kombobox einstellt. (Wie schon im vorigen Post beschrieben).
2. Kompatibilität = false setzen
3. Speichern
4.  Adapter stoppen
5. Alle Objekte löschen
6. Adapter starten.
7. Daumen drücken

**Comment by phg2k** [comment]
Zwischenstand: jetzt sieht es gut aus! Ich füge jetzt weitere Handys hinzu.

**Comment by afuerhoff** [comment]
@phg2k, @mikweb2017 
Hallo, ich möchte mal nachfragen, ob es jetzt läuft?

**Comment by phg2k** [comment]
Ich bin noch am Testen - sieht aber immer noch gut aus ;-).

Danke dir!

**Comment by phg2k** [comment]
LEIDER, es läuft nun wieder nicht mehr.![image](https://user-images.githubusercontent.com/28537231/121803884-d3030e00-cc43-11eb-89c4-24ce19084bbb.png)
Auch nach erneutem Ausführen von:
In der Konfiguration den Button Familienmitglieder hinzufügen drücken und kontrollieren (FRITZBOX), das das richtige aktive Device ausgewählt ist. Nicht eine deaktive Kopie mit anderer Mac Adresse (Es gibt mit gleichem Hostname unterschiedliche Einträge in der Fritzbox). Die sicherste Methode ist, wenn man Hostname in der Kombobox einstellt. (Wie schon im vorigen Post beschrieben).
Kompatibilität = false setzen
Speichern
Adapter stoppen
Alle Objekte löschen
Adapter starten. Jetzt sollten keine Objektleichen mehr vorhanden sein.
Daumen drücken

Stimmen die States nicht.
Nur 1 Phone connected. Erkennung über IP.
PresenceAll = true
Presence = false :-(

**Comment by phg2k** [comment]
UPDATE:
Es geht in einer Gruppe:
![image](https://user-images.githubusercontent.com/28537231/121804027-8b30b680-cc44-11eb-8089-9ab1a572cea3.png)
in den familyMembers wird es falsch angezeigt:

(WLAN gerade aus, daher stimmt absence=true)

**Comment by afuerhoff** [comment]
Hallo,

es scheint ein Problem mit doppelten Einträgen in der Konfiguration zu geben. Das muss ich mir mal genauer ansehen. Ist ja eigentlich auch nicht logisch etwas doppelt anzugeben. 
Setz mal bei phgS20ultra die Erkennung auf Hostname. Dann sollte es gehen. Weiterhin gelten die presenceAll, absenceAll States immer nur für die jeweilige Gruppe. Wenn keine Gruppe angegeben ist, dann wird das als Gruppe mit leerem Namen aufgefasst und die States direkt unter familyMembers angelegt. Es gibt z.B. keine presenceAll über alle Gruppen. Zugegeben, das mit den fehlenden Gruppen Namen ist etwas verwirrend. Evtl. ändere ich das noch bei Kompatibilität = false.

**Comment by afuerhoff** [comment]
Ich habe eine neue Version auf github hochgeladen. Bitte testen.

**Comment by phg2k** [comment]
Teste ich gerne!
Zum Thema doppelte: bei sind jeweils die Einträge für die beiden WLAN Frequenzbänder 2,4 / 5 je Hand in der Box. Das sieht nach Doppeleintrag aus, stimmt aber. Die Handys verbinden je nach Verfügbarkeit...

**Comment by afuerhoff** [comment]
Hallo, konntest du schon testen. Ich hab noch ein Update eingespielt.

**Comment by phg2k** [comment]
Hi!
Mit dem ersten Update lief es prima.
Ich teste mit dem Neuen weiter!
VG

afuerhoff ***@***.***> schrieb am Do., 17. Juni 2021, 19:03:

**Comment by afuerhoff** [comment]
Es gibt jetzt die Version 1.1.7 im Latest Repository. Bitte testen.

**Comment by mikweb2017** [comment]
Work fine Now!
alles super jetzt!!

**Comment by phg2k** [comment]
Bei mir leider nun sowohl absence als auch presence gleichzeitig auf true :-(.
Ich habe den Adapter bzw die Instanz gestoppt und dann alle Objekte gelöscht.
Dann wieder aktiviert.

**Comment by phg2k** [comment]
Update: scheint jetzt wiede rzu klappen. Ich beobachte es weiter und melde mich!
