### ISSUE TITLE
special characters are not allowed in password

### ISSUE THREAD

**Issue by Hosenroller** [afuerhoff/ioBroker.fb-checkpresence#53]
my password in the fritzbox have an " inside. But it is not possible so save an password in the adapter.
--> save button will disabled as soon as I type "

I have tested with beta and github version

allowed should be 
_ - ! " # $ % & ' ( ) * + , . / : ; < = > ? @ [ \ ] ^ ` { | } ~

please see https://service.avm.de/help/de/FRITZ-Box-Fon-WLAN-7490/014/hilfe_zeichen_fuer_kennwoerter

**Comment by afuerhoff** [comment]
Hello,
I have just published a test version on Github. Could you please test it and give feedback if it works for you. Thanks

**Comment by Hosenroller** [comment]
@afuerhoff  for me is it working now.
THANK YOU 

Only one comment:
according to https://service.avm.de/help/de/FRITZ-Box-Fon-WLAN-7490/014/hilfe_zeichen_fuer_kennwoerter
AVM allow not  öäüÖÄÜß§´ but inside of the adapter it is allowed to input --> I think this is OK. The User must input an valid and working password anyhow.

**Comment by afuerhoff** [comment]
I have checked this again. There was a failure in the pattern. Now it should work correctly. If you want you can test it again. 
A new version is on github.

**Comment by afuerhoff** [comment]
It is fixed with version v1.1.7. The version is in the latest repository now.
