### ISSUE TITLE
Adapter 1.1.5 wird von Iobroker beendet und lässt sich nicht mehr starten

### ISSUE THREAD

**Issue by peoples0815** [afuerhoff/ioBroker.fb-checkpresence#54]
Iobroker wurde schon neu gestartet, und Fritzbox (os 7.25) auch neu gestartet.

Alles kein Effekt.

- 2021-06-11 20:03:57.997 - info: host.Iobroker-Produktiv "system.adapter.fb-checkpresence.0" disabled
- 2021-06-11 20:03:57.999 - info: host.Iobroker-Produktiv stopInstance system.adapter.fb-checkpresence.0 (force=false, process=true)
- 2021-06-11 20:03:58.011 - info: fb-checkpresence.0 (27631) Got terminate signal TERMINATE_YOURSELF
- 2021-06-11 20:03:58.013 - info: fb-checkpresence.0 (27631) cleaned everything up ...
- 2021-06-11 20:03:58.014 - info: host.Iobroker-Produktiv stopInstance system.adapter.fb-checkpresence.0 send kill signal
- 2021-06-11 20:03:58.513 - info: fb-checkpresence.0 (27631) terminating
- 2021-06-11 20:03:58.514 - info: fb-checkpresence.0 (27631) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

**Comment by afuerhoff** [comment]
Aus dem Logauschnitt geht der Grund nicht hervor. Bitte vom Start bis zum Abbruch posten und dazu den Loglevel auf debug unter Instanzen setzen.

**Comment by peoples0815** [comment]
- 2021-06-12 14:17:50.210 -&nbsp;info: host.Iobroker-Produktiv "system.adapter.fb-checkpresence.0" enabled
--
- 2021-06-12 14:17:50.269 -&nbsp;info: host.Iobroker-Produktiv instance system.adapter.fb-checkpresence.0 started with pid 3109
- 2021-06-12 14:17:50.709 -&nbsp;debug: fb-checkpresence.0 (3109) Redis Objects: Use Redis connection: 127.0.0.1:9001
- 2021-06-12 14:17:50.728 -&nbsp;debug: fb-checkpresence.0 (3109) Objects client ready ... initialize now
- 2021-06-12 14:17:50.730 -&nbsp;debug: fb-checkpresence.0 (3109) Objects create System PubSub Client
- 2021-06-12 14:17:50.730 -&nbsp;debug: fb-checkpresence.0 (3109) Objects create User PubSub Client
- 2021-06-12 14:17:50.731 -&nbsp;debug: fb-checkpresence.0 (3109) Objects client initialize lua scripts
- 2021-06-12 14:17:50.752 -&nbsp;debug: fb-checkpresence.0 (3109) Objects connected to redis: 127.0.0.1:9001
- 2021-06-12 14:17:50.759 -&nbsp;debug: fb-checkpresence.0 (3109) objectDB connected
- 2021-06-12 14:17:50.760 -&nbsp;debug: fb-checkpresence.0 (3109) Redis States: Use Redis connection: 127.0.0.1:9000
- 2021-06-12 14:17:50.766 -&nbsp;debug: fb-checkpresence.0 (3109) States create System PubSub Client
- 2021-06-12 14:17:50.766 -&nbsp;debug: fb-checkpresence.0 (3109) States create User PubSub Client
- 2021-06-12 14:17:50.816 -&nbsp;debug: fb-checkpresence.0 (3109) States connected to redis: 127.0.0.1:9000
- 2021-06-12 14:17:50.817 -&nbsp;debug: fb-checkpresence.0 (3109) statesDB connected
- 2021-06-12 14:17:50.962 -&nbsp;info: fb-checkpresence.0 (3109) starting. Version 1.1.5 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.16.3, js-controller: 3.2.16
- 2021-06-12 14:17:57.031 -&nbsp;warn: fb-checkpresence.0 (3109) onReady: Fb init: getSSLPort: DeviceInfo:1 GetSecurityPort timeout of 6000ms exceeded
- 2021-06-12 14:17:57.059 -&nbsp;info: host.Iobroker-Produktiv "system.adapter.fb-checkpresence.0" disabled
- 2021-06-12 14:17:57.062 -&nbsp;info: host.Iobroker-Produktiv stopInstance system.adapter.fb-checkpresence.0 (force=false, process=true)
- 2021-06-12 14:17:57.068 -&nbsp;info: fb-checkpresence.0 (3109) Got terminate signal TERMINATE_YOURSELF
- 2021-06-12 14:17:57.072 -&nbsp;info: fb-checkpresence.0 (3109) cleaned everything up ...
- 2021-06-12 14:17:57.100 -&nbsp;info: host.Iobroker-Produktiv stopInstance system.adapter.fb-checkpresence.0 send kill signal
- 2021-06-12 14:17:57.573 -&nbsp;info: fb-checkpresence.0 (3109) terminating
- 2021-06-12 14:17:57.574 -&nbsp;info: fb-checkpresence.0 (3109) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
- 2021-06-12 14:17:58.101 -&nbsp;info: host.Iobroker-Produktiv stopInstance system.adapter.fb-checkpresence.0 killing pid 3109
- 2021-06-12 14:17:58.167 -&nbsp;info: host.Iobroker-Produktiv instance system.adapter.fb-checkpresence.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
- 2021-06-12 14:18:14.014 -&nbsp;info: javascript.0 (19822) script.js.Wandtablet.Bewegungsmelder: Bild wurde als camImagesbewegungsmelder_0.jpg gespeichert

**Comment by afuerhoff** [comment]
Hallo, die Fritzbox reagiert auf die Requests nicht. Das sieht nach einer Blockade des Users aus nach mehreren Fehlversuchen sich zu authentifizieren. 
1. User und Passwort prüfen
2. Konfiguration speichern
3. Adapter stoppen 
4. Fritzbox neu starten
5. Adapter starten wenn Fritzbox online

**Comment by peoples0815** [comment]
- User und PW stimmen
- Konfiguration gespeichert
- Adapter gestoppt
- Fritzbox neu gestartet
- Adapter ein
- gleiches Problem.
- downgrade auf Version kleiner 1.1.4
- funktioniert wunderbar

**Comment by afuerhoff** [comment]
Das kann eigentlich nicht sein. Die Änderung zwischen 1.1.5 und 1.1.4 ist so minimal und kommt auch im Programmfluss erst nach der Warnmeldung im Log.
Die Warnmeldung sagt aus, dass keine Antwort von der Fritzbox kommt.

Sieht das Log jetzt anders aus in der 1.1.5?

**Comment by peoples0815** [comment]
Ich habe den ganzen Iobroker mal neu gestartet, nun ging der Adapter auf grün (stand 12:45 Uhr)

Ich warte mal bis heute Abend und schreiben dann nochmal eine Info ob das nach wie vor so ist

**Comment by peoples0815** [comment]
Seit dem Neustart des Iobrokers läuft der Adapter fehlerfrei
