### ISSUE TITLE
presence always true

### ISSUE THREAD

**Issue by mcbirne** [afuerhoff/ioBroker.fb-checkpresence#57]
Hello, 
since I installed the new version I have the problem, that the presence is allays true.
After the installation of the new version I delete all objects from fb-chekpresence.
I defined 4 familyMembers.
If I switche the WiFi of my phone off,the state familyMembers.Hartmut.presence doesn't change.

**Comment by mcbirne** [comment]
If I switch the WIFI off I see Hartmut in the absentMembers. So it detact that Hartmut is not in the WIFI but the Hartmut. presence is true

**Comment by afuerhoff** [comment]
Could you please test the github version. I have made some smaler changes there. You can install it over the cat symbol in iobroker on the adapter page. The version has also 1.1.5 as version number. Its only for test.

**Comment by mcbirne** [comment]
Thanks, now it works.

**Comment by afuerhoff** [comment]
It is fixed with version v1.1.7. The version is in the latest repository now.
