### ISSUE TITLE
2x Mac Adressen für ein Familienmitglied

### ISSUE THREAD

**Issue by Snago636** [afuerhoff/ioBroker.fb-checkpresence#59]
Hallo,

erstmal vielen dank für diesen tollen Adapter. Aber ich hätte da mal zwei Fragen. 

1. Unsere neuen Handys nutzen meist 2 verschieden MAC für das Wlan, so wie es ausieht eine für 2,4 und eine 5. Besteht die Möglichkeit das man bei einem Familienmitglied 2 MAC hinterlegt. Mir werden meistens 2 Devices angelegt was so ein bissel unpraktisch ist.

2. Wenn ich Geräte aus dem Gast Wlan als Familienmitglied hinzufüge funktioniert das ja. Aber nach einigen Tagen vergisst die Fritzbox dieses Gerät und dann kommt immer folgender LogEintrag.
-> (30053) getActive Galaxy-Note20-Ultra: Warning: The configured mac-address for member Galaxy-Note20-Ultra was not found. Please insert a valid mac-address!
Ansich wäre dies kein Problem da es ja irgendwann wieder in der FB da ist aber er scheint dann nicht weiter die Geräte abzufragen.  Erst wenn ich das Gerät dann lösche zeigt er mir das nächste an wo ein Mac problem besteht.

gruß Snago

**Comment by afuerhoff** [comment]
Hallo, 

1.) du kannst ja den Status über den Hostnamen abfragen. In der Konfiguration einfach von MAC nach Hostname umstellen.
Man muss nur darauf achten, dass das Device in der Fritzbox richtig konfiguriert ist und nicht unterschiedliche Hostnamen hat. 

2.) Muss ich mir mal anschauen

**Comment by afuerhoff** [comment]
Hallo, ich habe ein Update auf Github hochgeladen. Das kannst Du einmal per Katzensymbol auf der Adapterseite per URL installieren und testen. Jetzt sollten für jedes Familienmitglied, das eine nicht vorhandene MAC Adresse hat, eine Warnmeldung kommen und zwar genau einmal. Ich hoffe, ich habe Deinen 2. Punkt richtig verstanden.

**Comment by santa81** [comment]
Viele neue Telefone benutzen eine virtuelle Mac Adresse und diese ist in jedem wlan anders.
Wenn du in den wlan Einstellungen die Mac Adresse auf Telefon Mac umstellst, dann hast du nicht mehr das Problem unterschiedliche Adressen zu haben.

**Comment by afuerhoff** [comment]
@santa81 
Eine Einschränkung. Es gibt wohl auch Handys bei denen man das nicht einstellen kann. In dem Fall kann man den Modus mit dem Hostnamen verwenden.

**Comment by afuerhoff** [comment]
@Snago636  
Hallo, es gibt die Version 1.1.7 im Latest Repository. Bitte testen

**Comment by Snago636** [comment]
@afuerhoff 
Hallo, vielen dank für die schnelle Hilfe, hatte gestern leider nicht so viel Zeit zum testen. 

zu 1.) Also mit den Hostnamen hatte ich noch garnicht gesehen, hatte nur MAC und IP in Erinnerung. Das habe ich jetzt mal umgestellt und teste ob es klappt. 

zu 2.) Das funktioniert jetzt super. So sehe ich gleich bei wem es Probleme gibt. Ich hatte manchmal Devices die nicht aktualisiert wurden. Dachte das der Adapter nach dem ersten Problem nicht weiter die anderen abgefragt hat. Werde es jetzt nochmal beobachten. 

3. Kann man vielleicht die Warnmeldung selbst deaktivieren und aktivieren? Durch mein Gästewlan hab ich auch User wo ganz oft der Log Eintrag kommt und da irritiert es doch das mein Log immer diese Warnmeldungen wegen der MAC hat. So Quasi vielleicht als Häkchen im Adapter oder als Objekt mit true/false, damit ich regelmäßig alle prüfen kann ohne das immer die Meldungen kommen.
 
Wenn es zuviel aufwand macht oder sinnlos erscheint einfach 3. ignorieren.  ;)

**Comment by afuerhoff** [comment]
Zu 3. Die Warnmeldung kommt für jedes Familienmitglied eigentlich nur einmal nach Start des Adapters.

**Comment by Snago636** [comment]
@afuerhoff 
zu 3. Sorry hab in letzter Zeit so viel mit dem Adapter rumgespielt das mir das nicht aufgefallen ist. 
zu 1 und 3 funktioniert bei mir jetzt wie gewünscht.

Vielen Dank für deine mühe. Von mir aus kann das issue geschlossen werden.

**Comment by afuerhoff** [comment]
Mit Version 1 1.7 behoben.
