### ISSUE TITLE
Add unit in data points

### ISSUE THREAD

**Issue by FredF63** [afuerhoff/ioBroker.fb-checkpresence#61]
Asuming the unit is minutes, it would be helpful to see this unit in the state 
fb-checkpresence.0.xxx.absent.since and 
fb-checkpresence.0.xxx.absent.sum_day

**Comment by afuerhoff** [comment]
Hi, I have uploaded a new version on github. You can test it, if you want.

**Comment by afuerhoff** [comment]
The new version 1.1.8 is now in the latest repository.

**Comment by FredF63** [comment]
Update gemacht, Einheiten da, super....
