### ISSUE TITLE
fb-checkpresence.1 will auf fb-checkpresence.0 zugreifen

### ISSUE THREAD

**Issue by pickerth** [afuerhoff/ioBroker.fb-checkpresence#65]
Habe eine FB 6490 im Netz 192.168.178.x und bei meiner Freundin eine FB 6530 im Netz 192.168.1.x die per VPN verbunden sind, so das ich auf beide interne Netze zugreifen kann, iobroker läuft auf 192.168.178.27

Wenn ich fb-checkpresence.1 neu starte, kommt in der Log Zb: fb-checkpresence.0.Steffen müsste aber eigentlich so sein fb-checkpresence.1.Steffen
Mit Familienmitglieder hinzufügen, öffnet sich das Fenster aber ohne Geräte zur Auswahl, früher ging das mal.
Er schreibt aber in den richtigen Datenpunkt wenn jemand kommt und geht.

Den Fehler
fb-checkpresence.1 | 2021-09-13 15:28:28.803 | warn | getExtIp:
habe ich nur bei dieser Instanz

fb-checkpresence.1 | 2021-09-13 14:47:51.144 | warn | The state "fb-checkpresence.0.Steffen" will not longer exist in a future version. Please use "fb-checkpresence.0.Steffen.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:50.790 | warn | The state "fb-checkpresence.0.Rosi" will not longer exist in a future version. Please use "fb-checkpresence.0.Rosi.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:50.601 | warn | The state "fb-checkpresence.0.Mario2" will not longer exist in a future version. Please use "fb-checkpresence.0.Mario2.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:50.442 | warn | The state "fb-checkpresence.0.Henry" will not longer exist in a future version. Please use "fb-checkpresence.0.Henry.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:50.253 | warn | The state "fb-checkpresence.0.Andy" will not longer exist in a future version. Please use "fb-checkpresence.0.Andy.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:49.495 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.1 | 2021-09-13 14:47:49.494 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.1 | 2021-09-13 14:47:49.494 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:49.493 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.1 | 2021-09-13 14:47:49.491 | warn | You should then manually delete the old states!
fb-checkpresence.1 | 2021-09-13 14:47:49.491 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.1 | 2021-09-13 14:47:49.444 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.443 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.442 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.440 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.440 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.439 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.438 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.437 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.436 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.435 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.434 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.433 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.432 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.430 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.428 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-13 14:47:49.427 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
#########################################################################################

Restart von fb-checkpresence.0

fb-checkpresence.0 | 2021-09-13 15:18:09.718 | warn | The state "fb-checkpresence.0.LuftentfeuchterGosund-7739" will not longer exist in a future version. Please use "fb-checkpresence.0.LuftentfeuchterGosund-7739.presence" instead!
fb-checkpresence.0 | 2021-09-13 15:18:09.545 | warn | The state "fb-checkpresence.0.DoogeeS68Pro" will not longer exist in a future version. Please use "fb-checkpresence.0.DoogeeS68Pro.presence" instead!
fb-checkpresence.0 | 2021-09-13 15:18:08.690 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-09-13 15:18:08.689 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-09-13 15:18:08.689 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-09-13 15:18:08.688 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-09-13 15:18:08.686 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-09-13 15:18:08.685 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!

**Comment by afuerhoff** [comment]
Hallo, ich habe auf Github eine neue Testversion hochgeladen. Bitte testen, ob der Fehler mit dem Zugriff auf die falsche Instanz behoben ist. Das Problem mit getExtIP kommt aufgrund einer falschen Konfiguration zustande. Sieht man auch im Log, dass dort viele Features deaktiviert sind. Mit der neuen Version sollte der Log Eintrag auch nicht mehr kommen. Du solltest aber die Konfiguration prüfen. Entweder hat der Fritzbox User nicht die richtigen Rechte oder der User ist  mit Passwort im Adapter nicht richtig hinterlegt.

**Comment by pickerth** [comment]
Hi, er greift jetzt auf die richtige Instanz zu, und der getExtIp: Fehler ist auch weg.
Wegen den Benutzerrechten, das schaue ich mir noch mal in Ruhe an.
Vielen Dank :-)

Log nach restart mit der neuen Version:

fb-checkpresence.0 | 2021-09-14 15:34:56.015 | warn | The state "fb-checkpresence.0.LuftentfeuchterGosund-7739" will not longer exist in a future version. Please use fb-checkpresence.0.LuftentfeuchterGosund-7739.presence" instead!
fb-checkpresence.0 | 2021-09-14 15:34:55.809 | warn | The state "fb-checkpresence.0.DoogeeS68Pro" will not longer exist in a future version. Please use fb-checkpresence.0.DoogeeS68Pro.presence" instead!
fb-checkpresence.0 | 2021-09-14 15:34:54.945 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-09-14 15:34:54.944 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-09-14 15:34:54.941 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-09-14 15:34:54.940 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-09-14 15:34:54.934 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-09-14 15:34:54.933 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.1 | 2021-09-14 15:34:02.741 | warn | The state "fb-checkpresence.1.Steffen" will not longer exist in a future version. Please use fb-checkpresence.1.Steffen.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:02.534 | warn | The state "fb-checkpresence.1.Rosi" will not longer exist in a future version. Please use fb-checkpresence.1.Rosi.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:02.330 | warn | The state "fb-checkpresence.1.Mario2" will not longer exist in a future version. Please use fb-checkpresence.1.Mario2.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:02.043 | warn | The state "fb-checkpresence.1.Henry" will not longer exist in a future version. Please use fb-checkpresence.1.Henry.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.876 | warn | The state "fb-checkpresence.1.Andy" will not longer exist in a future version. Please use fb-checkpresence.1.Andy.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.086 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.086 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.085 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.085 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.1 | 2021-09-14 15:34:01.083 | warn | You should then manually delete the old states!
fb-checkpresence.1 | 2021-09-14 15:34:01.082 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.1 | 2021-09-14 15:34:01.039 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.038 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.038 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.037 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.036 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.036 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.035 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.035 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.034 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.033 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.032 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.032 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.031 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.029 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.028 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.1 | 2021-09-14 15:34:01.027 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!

**Comment by afuerhoff** [comment]
Ist in der Version 1.1.10 gefixed
