### ISSUE TITLE
Adapter verliert häufig die "Verbidnung"

### ISSUE THREAD

**Issue by Scotty-89** [afuerhoff/ioBroker.fb-checkpresence#66]
Hallo,

ich nutze den Adapter seit kurzem da er ein paar Vorteile hat.
leider muss ich feststellen das der Adapter bei mir öfters die Verbindung verliert und mein Skript ihn dann neustartet.
ist euch das bekannt? 

zudem bekomme ich solche Meldungen:

checkPresence: getDeviceList: Hosts:1 X_AVM-DE_GetHostListPath: timeout of 6000ms exceeded

**Comment by afuerhoff** [comment]
Hallo, bei mir läuft er absolut stabil. Ein paar mehr Informationen wären hilfreich. Bitte mal das Log in der Logstufe debug posten. Vom Start bis zur Fehlermeldung. Die Meldung kommt häufig, wenn keine Verbindung zur Fritzbox besteht. Dann könnte die Fritzbox das TR064 Interface blockieren. Wenn sie ständig kommt hilft ein Neustart der Fritzbox.

**Comment by Scotty-89** [comment]
Hey,

also jetzt hab ich es auch einmal umgestellt und infos bekommen ;) 

`
<html>
<body>


fb-checkpresence.0 | 2021-09-24 21:05:07.421 | debug | loop family ends after 1,585799219 s
-- | -- | -- | --
fb-checkpresence.0 | 2021-09-24 21:04:57.833 | debug | loop main ends after 0,186983036 s
fb-checkpresence.0 | 2021-09-24 21:04:55.645 | debug | loop family ends after 0,848705090 s
fb-checkpresence.0 | 2021-09-24 21:04:44.791 | debug | loop family ends after 0,823910690 s
fb-checkpresence.0 | 2021-09-24 21:04:33.962 | debug | loop family ends after 1,333084063 s
fb-checkpresence.0 | 2021-09-24 21:04:22.629 | debug | loop family ends after 1,782291361 s
fb-checkpresence.0 | 2021-09-24 21:04:10.842 | debug | loop family ends after 0,803246666 s
fb-checkpresence.0 | 2021-09-24 21:04:00.031 | debug | loop family ends after 0,862391962 s
fb-checkpresence.0 | 2021-09-24 21:03:51.164 | debug | loop main ends after 0,183448899 s
fb-checkpresence.0 | 2021-09-24 21:03:48.979 | debug | loop family ends after 3,14848135 s
fb-checkpresence.0 | 2021-09-24 21:03:35.956 | debug | loop family ends after 1,346142630 s
fb-checkpresence.0 | 2021-09-24 21:03:24.608 | debug | loop family ends after 1,536693308 s
fb-checkpresence.0 | 2021-09-24 21:03:13.059 | debug | loop family ends after 1,412288156 s
fb-checkpresence.0 | 2021-09-24 21:03:01.641 | debug | loop family ends after 1,41673490 s
fb-checkpresence.0 | 2021-09-24 21:02:50.597 | debug | loop family ends after 1,503630375 s
fb-checkpresence.0 | 2021-09-24 21:02:41.085 | debug | loop main ends after 0,189972062 s
fb-checkpresence.0 | 2021-09-24 21:02:38.893 | debug | loop family ends after 1,667036927 s
fb-checkpresence.0 | 2021-09-24 21:02:27.216 | debug | loop family ends after 1,541246653 s
fb-checkpresence.0 | 2021-09-24 21:02:15.671 | debug | loop family ends after 2,197432430 s
fb-checkpresence.0 | 2021-09-24 21:02:03.472 | debug | loop family ends after 0,934565615 s
fb-checkpresence.0 | 2021-09-24 21:01:52.534 | debug | loop family ends after 2,84811213 s
fb-checkpresence.0 | 2021-09-24 21:01:40.445 | debug | loop family ends after 1,376561318 s
fb-checkpresence.0 | 2021-09-24 21:01:31.061 | debug | loop main ends after 0,192020551 s
fb-checkpresence.0 | 2021-09-24 21:01:28.868 | debug | loop family ends after 2,96461751 s
fb-checkpresence.0 | 2021-09-24 21:01:25.771 | info | loop successfully started
fb-checkpresence.0 | 2021-09-24 21:01:25.770 | info | states successfully subscribed
fb-checkpresence.0 | 2021-09-24 21:01:25.769 | info | createMemberObjects finished successfully
fb-checkpresence.0 | 2021-09-24 21:01:25.769 | info | History function for Scott disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-09-24 21:01:25.628 | warn | The state "fb-checkpresence.0.Scott" will not longer exist in a future version. Please use "fb-checkpresence.0.Scott.presence" instead!
fb-checkpresence.0 | 2021-09-24 21:01:25.627 | info | History function for Cynthia disabled. Please select a history adapter in the configuration dialog!
fb-checkpresence.0 | 2021-09-24 21:01:25.494 | warn | The state "fb-checkpresence.0.Cynthia" will not longer exist in a future version. Please use "fb-checkpresence.0.Cynthia.presence" instead!
fb-checkpresence.0 | 2021-09-24 21:01:25.165 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-09-24 21:01:24.783 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-09-24 21:01:24.782 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-09-24 21:01:24.782 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-09-24 21:01:24.782 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-09-24 21:01:24.780 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-09-24 21:01:24.779 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2021-09-24 21:01:24.748 | info | Layer3Forwarding1-GetDefaultConnectionService is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.748 | info | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.747 | info | WANPPPConnection1-ForceTermination is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.747 | info | DeviceConfig1-Reboot is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.747 | info | X_AVM-DE_HostFilter-GetWANAccessByIP is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.747 | info | X_AVM-DE_HostFilter-DisallowWANAccessByIP is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.746 | info | DeviceInfo1-GetInfo is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.746 | info | WLANConfiguration3-GetSecurityKeys is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.746 | info | WLANConfiguration3-GetInfo is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.746 | info | WLANConfiguration3-SetEnable is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.746 | info | WANIPConnection1-GetInfo is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.745 | info | WANPPPConnection1-GetInfo is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.745 | info | WANCommonInterfaceConfig1-GetCommonLinkProperties is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.745 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.745 | info | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.744 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.744 | info | Hosts1-X_AVM-DE_GetMeshListPath is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.744 | info | Hosts1-X_AVM-DE_GetHostListPath is supported
fb-checkpresence.0 | 2021-09-24 21:01:24.743 | info | configuration default connection: 1.WANPPPConnection.1
fb-checkpresence.0 | 2021-09-24 21:01:24.743 | debug | configuration filter delay: 15
fb-checkpresence.0 | 2021-09-24 21:01:24.743 | debug | configuration guest info: false
fb-checkpresence.0 | 2021-09-24 21:01:24.742 | debug | configuration qr code: false
fb-checkpresence.0 | 2021-09-24 21:01:24.742 | debug | configuration ssl: true
fb-checkpresence.0 | 2021-09-24 21:01:24.742 | debug | configuration compatibility: true
fb-checkpresence.0 | 2021-09-24 21:01:24.741 | debug | configuration whitelist: true
fb-checkpresence.0 | 2021-09-24 21:01:24.741 | debug | configuration mesh info: false
fb-checkpresence.0 | 2021-09-24 21:01:24.741 | debug | configuration fb-devices false
fb-checkpresence.0 | 2021-09-24 21:01:24.741 | debug | configuration familymembers: [{"enabled":true,"group":"","familymember":"XXXXX","devicename":"XXXXXXXXX","macaddress":"XXXXXX","ipaddress":"XXXXXXXX","usage":"MAC","usefilter":true,"comment":""},{"enabled":true,"group":"","familymember":"XXXXXX","devicename":"XXXXXX","macaddress":"XxXXXX","ipaddress":"XXXXXXX","usage":"MAC","usefilter":true,"comment":""}]
fb-checkpresence.0 | 2021-09-24 21:01:24.740 | debug | configuration familymembers count: 2
fb-checkpresence.0 | 2021-09-24 21:01:24.740 | debug | configuration dateformat: <yyyy.mm.dd HH:MM:ss>
fb-checkpresence.0 | 2021-09-24 21:01:24.740 | debug | configuration history: <>
fb-checkpresence.0 | 2021-09-24 21:01:24.739 | debug | configuration user: <iobroker>
fb-checkpresence.0 | 2021-09-24 21:01:24.738 | info | start fb-checkpresence.0: FRITZ!Box 7490 version: 113.07.26 ip-address: "192.168.178.1" - interval devices: 1 min. - interval members: 10 s
fb-checkpresence.0 | 2021-09-24 21:01:23.315 | info | starting. Version 1.1.8 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.22.6, js-controller: 3.3.18
fb-checkpresence.0 | 2021-09-24 21:01:22.914 | debug | statesDB connected
fb-checkpresence.0 | 2021-09-24 21:01:22.913 | debug | States connected to redis: 127.0.0.1:9000
fb-checkpresence.0 | 2021-09-24 21:01:22.889 | debug | States create User PubSub Client
fb-checkpresence.0 | 2021-09-24 21:01:22.887 | debug | States create System PubSub Client
fb-checkpresence.0 | 2021-09-24 21:01:22.826 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
fb-checkpresence.0 | 2021-09-24 21:01:22.819 | debug | objectDB connected
fb-checkpresence.0 | 2021-09-24 21:01:22.811 | debug | Objects connected to redis: 127.0.0.1:9001
fb-checkpresence.0 | 2021-09-24 21:01:22.614 | debug | Objects client initialize lua scripts
fb-checkpresence.0 | 2021-09-24 21:01:22.613 | debug | Objects create User PubSub Client
fb-checkpresence.0 | 2021-09-24 21:01:22.611 | debug | Objects create System PubSub Client
fb-checkpresence.0 | 2021-09-24 21:01:22.545 | debug | Objects client ready ... initialize now
fb-checkpresence.0 | 2021-09-24 21:01:22.124 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
fb-checkpresence.0 | 2021-09-24 21:01:18.055 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2021-09-24 21:01:18.053 | info | terminating
fb-checkpresence.0 | 2021-09-24 21:01:17.545 | info | cleaned everything up ...
fb-checkpresence.0 | 2021-09-24 21:01:17.544 | info | Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.0 | 2021-09-24 21:01:14.305 | debug | loop family ends after 8,808226213 s
fb-checkpresence.0 | 2021-09-24 21:00:55.496 | debug | loop family ends after 0,812588273 s
fb-checkpresence.0 | 2021-09-24 21:00:44.681 | debug | loop family ends after 0,781450889 s
fb-checkpresence.0 | 2021-09-24 21:00:33.894 | debug | loop family ends after 1,313097802 s
fb-checkpresence.0 | 2021-09-24 21:00:22.579 | debug | loop family ends after 0,823546285 s
fb-checkpresence.0 | 2021-09-24 21:00:13.735 | debug | loop main ends after 0,687798394 s
fb-checkpresence.0 | 2021-09-24 21:00:11.045 | debug | loop family ends after 2,434465990 s


</body>
</html>`

**Comment by afuerhoff** [comment]
Im Log ist nichts auffälliges zu erkennen. Da brauche ich mehr Informationen. Könnte ja auch an deinem Netzwerk liegen. Wie sind ioBroker und Fritzbox verbunden? Wlan, Kabel? Wann passiert der Verbindungsabbruch. Wie sieht es zu dem Zeitpunkt im Log aus? ...

**Comment by Scotty-89** [comment]
Hey,

das ist alles per Kabelverbunden und sonst ist auch nichts weiter auffällig.

im log oben ist genau der Zeitpunkt mit drin ..

<html>
<body>


fb-checkpresence.0 | 2021-09-24 21:01:22.545 | debug | Objects client ready ... initialize now
-- | -- | -- | --
fb-checkpresence.0 | 2021-09-24 21:01:22.124 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
fb-checkpresence.0 | 2021-09-24 21:01:18.055 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2021-09-24 21:01:18.053 | info | terminating
fb-checkpresence.0 | 2021-09-24 21:01:17.545 | info | cleaned everything up ...
fb-checkpresence.0 | 2021-09-24 21:01:17.544 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by afuerhoff** [comment]
Hallo, hast Du das Problem eigentlich immer noch?

**Comment by Scotty-89** [comment]
Hey,

in der tat nicht das es mir aufgefallen ist...

**Comment by afuerhoff** [comment]
Problem hat sich erledigt
