### ISSUE TITLE
VPN Verbindung

### ISSUE THREAD

**Issue by Sacred-Shadow** [afuerhoff/ioBroker.fb-checkpresence#67]
Hey,

mal ne blöde Frage.
Gerade da der Adapter ja doch mehr als nur die Überwachung der WLAN User kann.

Kann man irgendwie auch den Status der VPN Verbindung auf der Fritz!Box mit rausziehen? 
Mir geht es darum zu erfahren, ob die VPN Verbindung aktiv ist oder nicht.

Bisher muss ich immer durch den Tunnel pingen um rauszubekommen, ob der aktiv ist.
Wäre aber iwie schöner, wenn man den Status direkt aus der Box auslesen könnte.

Grüße

**Comment by afuerhoff** [comment]
Hallo, in der nächsten Version wird es ein neues Attribut "vpn" an den FB-Devices geben.

**Comment by coltc50** [comment]
Hallo, VPN scheint bei Wireguard leider nicht korrekt aktualisiert zu werden... Ich bin von außerhalb per VPN eingewählt und leider zeigt mir FBCheckPrecence das ich anwesend bin...

**Comment by afuerhoff** [comment]
Hallo, 

hab deine Aussage nicht so ganz verstanden. 
Ist denn der Datenpunkt vpn am Device = true? Wenn eine Verbindung über VPN besteht, dann sollte auch das Device active = true sein. Hab selber keine VPN Verbindung und kann es leider im Moment nicht testen.
![image](https://user-images.githubusercontent.com/50245893/194651287-a25d98d2-1b7a-4cde-b949-1501cba876bf.png)

**Comment by coltc50** [comment]
Hallo, ich habe es anders gelöst bekommen. Ich hatte den Devicenamen und den Namen der VPN Verbindung gleich. Somit hat er beide Verbindungen dem selben Device zugeordnet. Habe das lokale Device nun anders benannt. Somit kann ich beides auseinander halten. VPN steht aber bei beiden false obwohl das eine Device über VPN angebunden ist...
Bin aber auch auf Beta Version Fritzbox 7530 ...
