### ISSUE TITLE
No presence states for familyMembers

### ISSUE THREAD

**Issue by MikeHellracer** [afuerhoff/ioBroker.fb-checkpresence#68]
Hi, 
ich habe über den Adapter unterhalb des Ordners familiyMembers einen für Eltern und Großeltern angelegt.
Es werden aber nur die presence states innerhalb der Ordner angezeigt also ist "jemand der Eltern" da oder "jemand der Großeltern da". 
Leider habe ich keine konsolidierten presence states.
Also ist "jemand aus der Familie da"?

**Comment by afuerhoff** [comment]
Bitte mal die Konfiguration posten.

**Comment by MikeHellracer** [comment]
anbei die Konfiguration.
Dabei werden unterhalb des Knoten FamilyMembers 2 Ordner Eltern & Großeltern angelegt. Innerhalb dieser Ordner werden auch die DP für presence, absence,m cnt, etc. korrekt angezeigt.
Aber ich habe keinerlei DP im Knoten Familyembers um zu erfahren, ob denn irgendeiner aus der Familie da ist.

![image](https://user-images.githubusercontent.com/59908487/140887494-f100a05a-ac06-49cf-9b73-e7445ff6a88f.png)

**Comment by afuerhoff** [comment]
Kannst du einmal die Objekte unter Familymembers posten. Die Struktur reicht.

**Comment by MikeHellracer** [comment]
![Screenshot_20211109_182302_com android chrome](https://user-images.githubusercontent.com/59908487/140973721-ce0acf25-4317-4b40-8c75-f0e92c20c09b.jpg)

**Comment by afuerhoff** [comment]
Hallo, auf der Wurzel werden keine konsolidierten Datenpunkte für die Gruppen angelegt. Die werden nur angelegt, wenn man ein Familienmitglied ohne Gruppe eingibt. Die beziehen sich dann aber auch nur auf die Familienmitglieder ohne Gruppe. 
Heißt, dass nur innerhalb einer Gruppe konsolidiert wird.

**Comment by MikeHellracer** [comment]
Ich habe das ohne Gruppen versucht. Aber dann wurden die "Ordner" nicht mehr unterhalb 
von  FamilyMembers angelegt, sondern eine Ebene darüber.
Könnte man (du) die konsolidierten Angaben für FamilyMembers nicht noch einbauen?

**Comment by afuerhoff** [comment]
Du musst die Kompatibilität ausschalten. Dann wird alles unter familymembers angelegt.

**Comment by MikeHellracer** [comment]
Hi, könnte man (du) das noch einbauen.
So kann ich auch erfahren ob irgendein FamilyMember da ist

**Comment by afuerhoff** [comment]
Problem gelöst. Wird geschlossen.
