### ISSUE TITLE
Nach Update Fritzbox auf 7.29 keine Funktion mehr

### ISSUE THREAD

**Issue by jkbiz** [afuerhoff/ioBroker.fb-checkpresence#69]
Hallo zusammen,

seit dem Update der Fritzbox 6660 auf 7.29  funktioniert der Adapter nicht mehr korrekt und holt keine Daten ab. Der Adapter steht auf rot "Verbunden mit Gerät oder Dienst". Nach dem ich diesen neugestartet habe, erhalte ich unten aufgeführte Meldung.

Installiert ist der ioBroker 5.1.25 und der Adapter fb-checkpresence v1.1.10. Ein Update des Adapters auf eine aktuellere Version ist via Webinterface nicht möglich.

Hat jemand die gleichen Erfahrungen gemacht ?

Besten Dank für die Unterstützung und viele Grüße

fb-checkpresence.0 | 2021-11-17 21:09:55.874 | info | loop successfully started
-- | -- | -- | --
fb-checkpresence.0 | 2021-11-17 21:09:55.873 | info | states successfully subscribed
fb-checkpresence.0 | 2021-11-17 21:09:55.873 | warn | infoNoFamilyMembers: no family members defined! Objects are not created!
fb-checkpresence.0 | 2021-11-17 21:09:55.872 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-11-17 21:09:55.677 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-11-17 21:09:55.677 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-11-17 21:09:55.677 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-11-17 21:09:55.677 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-11-17 21:09:55.676 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-11-17 21:09:55.676 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.662 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-17 21:09:55.661 | info | configuration default connection: -
fb-checkpresence.0 | 2021-11-17 21:09:55.660 | info | start fb-checkpresence.0: FRITZ!Box 6660 Cable version: 252.07.29 ip-address: "192.168.178.254" - interval devices: 1 min. - interval members: 60 s
fb-checkpresence.0 | 2021-11-17 21:09:55.391 | info | starting. Version 1.1.10 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.22.7, js-controller: 3.3.15
fb-checkpresence.0 | 2021-11-17 21:09:52.410 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2021-11-17 21:09:52.409 | info | terminating
fb-checkpresence.0 | 2021-11-17 21:09:51.908 | info | cleaned everything up ...
fb-checkpresence.0 | 2021-11-17 21:09:51.907 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by afuerhoff** [comment]
Hallo, wie sieht denn deine Konfiguration aus? Es sind keine Familienmitglieder laut Log definiert. Auch die meisten Funktionen sind deaktiviert. Hast du einen User in der Fritzbox angelegt. Wie sind die Berechtigungen des Users. Evtl. die Fritzbox neu starten. Ein Log mit Loglevel debug wäre hilfreich.

**Comment by afuerhoff** [comment]
Ich habe heute auf 7.29 meine 7490 aktualisiert. Es funktioniert alles ohne Probleme.

**Comment by jkbiz** [comment]
Sorry die verspätete Antwort.
Der Adapter hat vorher funktioniert und ich konnte alle Teilnehmer sehen. Nach dem Update aber leider nicht mehr.
Anbei die Debug log. Da hier von nicht mehr unterstützen Funktionen die Rede war, dachte ich, poste ich es.




fb-checkpresence.0 | 2021-11-23 08:20:40.865 | info | loop successfully started
-- | -- | -- | --
fb-checkpresence.0 | 2021-11-23 08:20:40.863 | info | states successfully subscribed
fb-checkpresence.0 | 2021-11-23 08:20:40.862 | warn | infoNoFamilyMembers: no family members defined! Objects are not created!
fb-checkpresence.0 | 2021-11-23 08:20:40.850 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-11-23 08:20:39.860 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-11-23 08:20:39.854 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-11-23 08:20:39.853 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-11-23 08:20:39.852 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-11-23 08:20:39.850 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-11-23 08:20:39.845 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2021-11-23 08:20:39.812 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.811 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.811 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.810 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.810 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.809 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.809 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.808 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.807 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.807 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.807 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.806 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.806 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.805 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2021-11-23 08:20:39.805 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.804 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2021-11-23 08:20:39.804 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.803 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:20:39.802 | info | configuration default connection: -
fb-checkpresence.0 | 2021-11-23 08:20:39.799 | info | start fb-checkpresence.0: FRITZ!Box 6660 Cable version: 252.07.29 ip-address: "192.168.178.254" - interval devices: 1 min. - interval members: 60 s
fb-checkpresence.0 | 2021-11-23 08:20:39.223 | info | starting. Version 1.1.10 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.22.7, js-controller: 3.3.15
fb-checkpresence.0 | 2021-11-23 08:20:34.393 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
fb-checkpresence.0 | 2021-11-23 08:20:34.392 | info | terminating
fb-checkpresence.0 | 2021-11-23 08:20:33.890 | info | cleaned everything up ...
fb-checkpresence.0 | 2021-11-23 08:20:33.887 | info | Got terminate signal TERMINATE_YOURSELF
fb-checkpresence.0 | 2021-11-23 08:09:10.334 | info | loop successfully started
fb-checkpresence.0 | 2021-11-23 08:09:10.333 | info | states successfully subscribed
fb-checkpresence.0 | 2021-11-23 08:09:10.332 | warn | infoNoFamilyMembers: no family members defined! Objects are not created!
fb-checkpresence.0 | 2021-11-23 08:09:10.326 | info | createGlobalObjects finished successfully
fb-checkpresence.0 | 2021-11-23 08:09:08.677 | warn | The state "devices" will not longer exist in a future version. Please use "fb-devices.count" instead!
fb-checkpresence.0 | 2021-11-23 08:09:08.676 | warn | The state "activeDevices" will not longer exist in a future version. Please use "fb-devices.active" instead!
fb-checkpresence.0 | 2021-11-23 08:09:08.675 | warn | The state "blacklist" will not longer exist in a future version. Please use "blacklist.presence" instead!
fb-checkpresence.0 | 2021-11-23 08:09:08.675 | warn | The state "guest" will not longer exist in a future version. Please use "guest.presence" instead!
fb-checkpresence.0 | 2021-11-23 08:09:08.673 | warn | You should then manually delete the old states!
fb-checkpresence.0 | 2021-11-23 08:09:08.672 | warn | In an future version some states are not more existent. Please use compatibility = false to switch to the new handling of the states!
fb-checkpresence.0 | 2021-11-23 08:09:08.635 | warn | Layer3Forwarding1-GetDefaultConnectionService is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.635 | warn | LANConfigSecurity1-X_AVM-DE_GetCurrentUser is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.634 | warn | WANPPPConnection1-ForceTermination is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.634 | warn | DeviceConfig1-Reboot is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.633 | warn | X_AVM-DE_HostFilter-GetWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.633 | warn | X_AVM-DE_HostFilter-DisallowWANAccessByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.632 | warn | DeviceInfo1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.632 | warn | WLANConfiguration3-GetSecurityKeys is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.631 | warn | WLANConfiguration3-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.631 | warn | WLANConfiguration3-SetEnable is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.630 | warn | WANIPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.629 | warn | WANPPPConnection1-GetInfo is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.629 | warn | WANCommonInterfaceConfig1-GetCommonLinkProperties is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.628 | info | DeviceInfo1-GetSecurityPort is supported
fb-checkpresence.0 | 2021-11-23 08:09:08.628 | warn | Hosts1-X_AVM-DE_GetSpecificHostEntryByIP is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.627 | info | Hosts1-GetSpecificHostEntry is supported
fb-checkpresence.0 | 2021-11-23 08:09:08.626 | warn | Hosts1-X_AVM-DE_GetMeshListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.626 | warn | Hosts1-X_AVM-DE_GetHostListPath is not supported! Feature is deactivated!
fb-checkpresence.0 | 2021-11-23 08:09:08.625 | info | configuration default connection: -
fb-checkpresence.0 | 2021-11-23 08:09:08.621 | info | start fb-checkpresence.0: FRITZ!Box 6660 Cable version: 252.07.29 ip-address: "192.168.178.254" - interval devices: 1 min. - interval members: 60 s
fb-checkpresence.0 | 2021-11-23 08:09:07.737 | info | starting. Version 1.1.10 in /opt/iobroker/node_modules/iobroker.fb-checkpresence, node: v12.22.7, js-controller: 3.3.15

**Comment by jkbiz** [comment]
Familie Mitglieder kann ich nicht aufrufen bzw. auswählen, da hier keine Verbindung zur FB aufgebaut werden kann.

**Comment by afuerhoff** [comment]
Verstehe ich nicht so ganz. Hast du denn die vorher vorhandenen Familienmitglieder gelöscht? Hast du die Fritzbox mal rebootet? Der User ist mit den notwendigen Rechten angelegt? Passwort mal neu im Adapter eingegeben?

**Comment by afuerhoff** [comment]
@jkbiz 
Hallo, hast du die Probleme noch?

**Comment by jkbiz** [comment]
Hallo, ich habe ioBroker nun auf eine Docker Instanz umgezogen und die config per backup/restore wiederhergestellt. Jetzt läufts. Danke der Nachfrage und alles gute für 2022 :)
