### ISSUE TITLE
Mesh seems to be probelmatic

### ISSUE THREAD

**Issue by daniel-lo** [afuerhoff/ioBroker.fb-checkpresence#7]
Hi, the adapter shows the presence of wifi devices close to the main router but an iphone connected to a mesh device does not receive the present state.

**Comment by afuerhoff** [comment]
Hi, in my network the adapter receives connection states from iphones and android cellphones from the mesh repeaters. It seems to be a problem in your network.

**Comment by daniel-lo** [comment]
thanks .. it had indeed improved .. nevertheless the states are not reliable .. either the phone or the router disconnects intermittently.

**Comment by afuerhoff** [comment]
Hi. The iphone has a deep sleep mode. This can be the problem. If, it is ok for you, can you please close the issue or I can do.

**Comment by afuerhoff** [comment]
Hi, I close the issue now, because of no feedback.
