### ISSUE TITLE
Timestamps in familyMembers.json inconsistent with Active state

### ISSUE THREAD

**Issue by dilmash** [afuerhoff/ioBroker.fb-checkpresence#74]
When object "familyMembers.json" member changes Active state, the reported time stamps are not updated on first event. The next event provides proper time stamps however.

Event traces from Node-Red

Event 1: Device zzz has changed state from Active=true to Active=false
```
[
  {
    "Name": "zzzz",
    "Active": "false",
    "Kommt": "2022.01.12 14:52:53",
    "Geht": "2022.01.12 14:44:44"
  }
]
```
Timestamp for "Geht" is earlier than "Kommt" but "Active" is false. The timestamp "Geht" should however reflect the time the the device disconnected.

Next event (1 Minute later) has than a logical valid timestamp:
```
[
  {
    "Name": "zzzz",
    "Active": "false",
    "Kommt": "2022.01.12 14:52:53",
    "Geht": "2022.01.12 15:00:00"
  }
]
```
I use these events to send a message with name and timestamp when the last device logs out or the first device logs back in. It required some additional programming (verifying the timestamps) to create a message with plausible timestamps.

Thanks for a very useful program!

**Comment by afuerhoff** [comment]
Hello, 
thanks for the issue. I could reproduce the problem.
With the next version I am going to fix it.
