### ISSUE TITLE
Nach Neustart wird die Alias-ID für die Datenbank gelöscht

### ISSUE THREAD

**Issue by guergen1** [afuerhoff/ioBroker.fb-checkpresence#8]
Habe den Adapter seit ein paar Tagen installiert und mich gewundert, dass nach mehreren Tagen immer noch im Log folgenden Eintrag finde:
![grafik](https://user-images.githubusercontent.com/34395245/74262291-e410d780-4cfc-11ea-86e5-ea9c89493c15.png)

Habe darauf in der Datenbank nachgesehen und festgestellt, dass die Daten nicht per Alias, sondern als Datenpunkt gespeichert werden

![grafik](https://user-images.githubusercontent.com/34395245/74262359-00147900-4cfd-11ea-8fc4-0120fb391dcc.png)

obwohl es wie folgt im Adapter hinterlegt ist:

![grafik](https://user-images.githubusercontent.com/34395245/74262433-233f2880-4cfd-11ea-919e-a383132a6f70.png)

Wenn ich dann den Adapter neustarte, sieht es folgendermaßen aus: 

![grafik](https://user-images.githubusercontent.com/34395245/74262595-70bb9580-4cfd-11ea-80bb-fabec8df67bd.png)

Er schmeisst den Alias raus!

Der Adapter ist wie folgt konfiguriert: 
![grafik](https://user-images.githubusercontent.com/34395245/74262861-fb03f980-4cfd-11ea-81eb-a6ee4bd2531b.png)

Mein System: 
![grafik](https://user-images.githubusercontent.com/34395245/74262649-9183eb00-4cfd-11ea-88ce-2a1e1ea50076.png)

**Comment by afuerhoff** [comment]
Verhalten habe ich im Adapter in der aktuellen Version geändert. Der Alias wird jetzt ausgelesen und wieder gesetzt.
