### ISSUE TITLE
Guest state indicator not working

### ISSUE THREAD

**Issue by Claus1985** [afuerhoff/ioBroker.fb-checkpresence#89]
**Describe the bug**  
Even though a device is logged into the FB guest wifi the state in ioBroker is false.
Rest is working like a charme (state of registered users in main wifi).

**Expected behavior**  
State should be true.

**Screenshots & Logfiles**  
![FB_Options](https://user-images.githubusercontent.com/69499563/156930131-7dd31340-d5a7-4efa-bd12-dc7fae4e8dbc.PNG)
![AdapterOptions](https://user-images.githubusercontent.com/69499563/156930137-9ad7310c-2f05-48f1-86ba-b42844a07b34.PNG)

**Versions:**  
 - Adapter version: 1.1.13
 - JS-Controller version: 4.0.18
 - Node version: 14.19.0
 - Operating system: raspian 

Any advice how to fix this?

Thx and brgds,

Claus

**Comment by afuerhoff** [comment]
Hello, please select Fb-Geräte erstellen.

**Comment by afuerhoff** [comment]
@Claus1985 
Hello, have you performed the test with the option "Fb-Geräte erstellen"?

**Comment by Claus1985** [comment]
Hey, not until now, I’ll close this thread and reopen if problem still consists.
Thx for the help!
