### ISSUE TITLE
Datenpunkt Blacklist immer false

### ISSUE THREAD

**Issue by m-s-b** [afuerhoff/ioBroker.fb-checkpresence#91]
Der Datenpunkt Blacklist unter jedem Objekt im Ordner fb-devices bleibt immer false.
Objekte die nicht in der Whitelist sind sollten blacklist=true werden. Analog der Umsetzung bei der Whitelist, hier funktioniert es.

**Comment by afuerhoff** [comment]
Bitte die neue Version 1.1.4 im Latest testen und Rückmeldung geben

**Comment by m-s-b** [comment]
Läuft einwandfrei, alles was in der Blacklist ist hat jetzt "blacklist=true".
Danke!
