### ISSUE TITLE
Gast Netzwerk von Blacklist ausschließen

### ISSUE THREAD

**Issue by lu-mueller** [afuerhoff/ioBroker.fb-checkpresence#92]
Ich habe eine Whitelist mit allen meinen Geräten im privaten Netzwerk und sobald sich eine neues Gerät in mein privates Netzwerk einloggt soll dementsprechend blacklist auf true gesetzt werden. Dies funktioniert auch, allerdings setzten neue Geräte im Gastnetzwerk die Blacklist auch auf true. Ist es möglich alle Gäste von der Blacklist auszuschließen?

**Comment by afuerhoff** [comment]
Hallo, bitte die neue Version 1.1.14 im Latest testen und Rückmeldung geben.

**Comment by lu-mueller** [comment]
Funktioniert 👍🏼
Danke
